### ISSUE TITLE
Enable source maps for minified js files

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitplatform#1711]
We're using build web compiler 2022 to minify js results of typescript compiler in the following areas:

1- src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/wwwroot/scripts
2- src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Scripts/app.ts
3- src/Client/Web/Bit.Client.Web.BlazorUI/Scripts/bit.blazorui.ts

The toolings current configuration generates no source map for the minified file which results into poor developer experience while debugging our typescript codes

**Comment by msynk** [comment]
this issue is not valid anymore
