### ISSUE TITLE
Implement custom loading indicator for startup and authorizing phase in the TodoTemplate project

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitplatform#1768]
The default `Authorizing` template of `TodoTemplate` which is displayed during the user authorizing by system only displays a simple  message and it is little boring, not beautiful and not well recognizable

**Comment by ysmoradi** [comment]
Let's call this **authorizing phase**
Additional info:
I'd prefer not to tell the user about something that she can't understand.
A loading view that indicates app is loading would be enough
Note that this view is especially helpful for blazor hybrid where this step took a little bit longer
There is also another step that needs a loading indicator (while non pre-rendered blazor web assembly or blazor hybrid are being loaded). Let's call this **initializing phase**
The main difference between initializing and authorizing phases is that in initializing phase, we don't have access to blazor components while in authorizing phase we can use all blazor features.
I'd prefer to create something blazor independent (like the progress bar that we've in PWA mode) so we can use that in both scenarios.
@msynk @maryamhdr

**Comment by msynk** [comment]
@ysmoradi 
good points. let's discuss these further and submit separate issues if required.
