### ISSUE TITLE
Add `BitNumericTextField` component 

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#1846]
Add a Numeric textbox Component like the [Telerik numeric textbox](https://docs.telerik.com/blazor-ui/components/numerictextbox/overview). The numeric textbox is similar BitSpinButton in appearance but is structurally different. The component is a generic type. 
- You can set and get the value type of number.
- You can hide arrow button.
- You can set string format for display number.

**Comment by maryamhdr** [comment]
> Add a Numeric textbox Component like the Telerik numeric textbox. The numeric textbox is similar BitSpinButton in appearance but is structurally different. The component is a generic type.
> 
> * You can set and get the value type of number.
> * You can hide arrow button.
> * You can set string format for display number.

Could you add the Telerik component link plz?
@Cyrus-Sushiant 
ژشد
