### ISSUE TITLE
Iac (Infra as code) enhancements

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitplatform#1913]
- [ ] Rename AppDbConnectionString to SqlServerConnection
- [x] Remove aliases from app service
![image](https://user-images.githubusercontent.com/5352980/164960394-89b54b36-8647-46a5-a459-fd03d1167371.png)

**Comment by msangtarash** [comment]
this is closed .
we decided on separating tasks so it is not valid any more.
