### ISSUE TITLE
Use pulumi azure blob storage backend instead of a local folder in the `Iac` project of the templates

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#1949]
We are using file to keep snapshot of pulumi in ``TodoTemplate.Iac`` project.
It should be change the way to keep them in azure blob storage instead of file.

**Comment by msynk** [comment]
@msangtarash 
please provide enough amount of description in this issue for others to understand what's the problem.
and mention what project is this issue for (at least in the title), we have 3 major projects atm.
and also add the appropriate labels to the issue.

**Comment by msynk** [comment]
not planned yet
