### ISSUE TITLE
Using better app service & app insights integration in ``TodoTemplate.Iac`` project

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#1951]
Better app service & app insights integration. It's connected through an instrumentation key, but they can get connected much better. For example, we can tell app insights our app service is based on the .net 6 web app so it can monitor it better than before.
 
![image](https://user-images.githubusercontent.com/23101977/166106453-9e89d78d-9e97-4786-9896-de774db878c5.png)

**Comment by msynk** [comment]
@msangtarash 
please mention what project is this issue for (at least in the title) and also add the appropriate labels to the issue.
