### ISSUE TITLE
Add BitIcon component

### ISSUE THREAD

**Issue by MohammadJavadTabari** [bitfoundation/bitplatform#1963]
Implement the `BitIcon` component based on the corresponding Icon component in the Fluent UI library:

https://developer.microsoft.com/en-us/fluentui#/controls/web/icon

**Comment by msynk** [comment]
@MohammadJavadTabari 
I've updated the issue based on the Bit Open Source conventions.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
this issue is resolved in https://github.com/bitfoundation/bitplatform/issues/3037

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
