### ISSUE TITLE
Issues on the `BitSpinButton` demo page

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitplatform#2062]
There are some mistakes on the `BitSpinButton` demo page:

 - The description of `BitSpinButton`, `SpinButton With Icon`, `SpinButton With Suffix,` and `SpinButton With Label Above` sections are totally wrong, they are about the `BitFileUpload` component.
 
![descriptions](https://user-images.githubusercontent.com/46419023/169582624-34c73419-1646-470b-a462-7ce5876680b6.png)

- In the `SpinButton With Icon` section, we expect to see an icon beside the label of the `BitSpinButton` component, but there is no icon there.

![icons](https://user-images.githubusercontent.com/46419023/169582882-98ad1cc3-7c1f-49f2-9c4d-66bf58758f03.png)

**Comment by ysmoradi** [comment]
Really appreciate it @SomayeEbrahimi
