### ISSUE TITLE
Social buttons in components playground have some ui issues

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitplatform#2063]
1- Size issue:

![image](https://user-images.githubusercontent.com/5352980/169636872-b4bd6e27-562b-42e6-b95f-7f8425adfd83.png)

2- Background color issue: (The same background color for all of them!)

![image](https://user-images.githubusercontent.com/5352980/169636909-c76a72c5-80e5-4ca3-b7b0-fa4440d769ad.png)

**Comment by msynk** [comment]
the first one occurs on pages with a sidebar (so not on the home page even on small screens)

**Comment by msynk** [comment]
@ysmoradi 
what is wrong with the bg color of the hovered icons?

**Comment by ysmoradi** [comment]
> @ysmoradi about the second one: what is wrong with the bg color of the hovered icons?

They used to have background colors specific to each social network before
Now, they've the same background color

**Comment by ysmoradi** [comment]
> @ysmoradi about the second one: what is wrong with the bg color of the hovered icons?

They used to have background colors specific to each social network before
Now, they've the same background color

**Comment by msynk** [comment]
I see, any idea @maryamhdr ?

**Comment by maryamhdr** [comment]
> I see, any idea @maryamhdr ?

Yeah, I think what @ysmoradi mentions in this issue should be fixed.

**Comment by sajadkardel** [comment]
I fix it @maryamhdr
