### ISSUE TITLE
Test and implement the ComponentDetails API in the `BitActionButton` demo page

### ISSUE THREAD

**Issue by saeedhalab** [bitfoundation/bitplatform#2134]

**Comment by msynk** [comment]
@maryamhdr 
why did you close this issue?
I don't think this issue is redundant.

**Comment by maryamhdr** [comment]
> @maryamhdr why did you close this issue? I don't think this issue is redundant.

just wanted to move it to the V-Next :)
Thank you!

**Comment by msynk** [comment]
This is issue is now redundant, so I'm closing it.
