### ISSUE TITLE
Incorrect values for the `Type` in the result of the `ComponentDetails` API

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#2138]
The generic parameters `Type` has incorrect values in the results of the `ComponentDetails` API such as follows

![image](https://user-images.githubusercontent.com/6169846/171340627-3b081dd5-b34c-4bb2-9fd1-0bf9509af0fa.png)

**Comment by ysmoradi** [comment]
What is expected here? @msynk

**Comment by msynk** [comment]
hmmm, it is expected to return the correct values 😁
