### ISSUE TITLE
The AllowTextInput doesn't work correctly in date picker when enter two-digit numbers for day

### ISSUE THREAD

**Issue by Kamalifar** [bitfoundation/bitplatform#2151]
I set the "AllowTextInput" to "true".
When two-digit numbers are entered for the day until the first digit is entered, the date is guessed by it before the second digit is entered, unless the second digit is entered very quickly, which of course is sometimes useless.

**Expected behavior**
It seems better to give the user more time to enter the second digit.

**Bit Blazor client**
- Bit nuget package's version. 11.0.0
- Blazor Server or Blazor Web Assembly or both? Blazor Server
- Which browser? Chrome Version 102.0.5005.63 (Official Build) (64-bit)
- Which blazor version? blazor 6

**Comment by Kamalifar** [comment]
Thank you very much for resolving this issue
One problem that arises now is that it no longer considers the different modes of manual entry of date.
For example, in the previous version, if the user entered only the month and day, then this year was automatically selected, including the day and month, or there was no need for the user to enter both digits of the month or both digits of the day. Even if, for example, he entered 2/3, the date picker would be automatically selected on the third of Ordibehesht of this year.
However, now the whole date must be entered by observing the two digits of the month and day to determine the date. For example 1401/02/03.

**Comment by msynk** [comment]
@Kamalifar 
first of all, thank you very much for your feedback, it's very appreciated 👍.
for the last issue you've mentioned above, since the component has a specific parameter for date formatting, there is no straight or easy way to parse the custom inputs that are not matched exactly to the format specified by the user.
but for the record, I suggest you open another issue for this problem.
tyvm 😊

**Comment by Kamalifar** [comment]
@msynk 
Thank you, 

> there is no straight or easy way to parse the custom inputs that are not matched exactly to the format specified by the user.
But this feature was present in the previous version. Anyway, I'm creating a new issue.
