### ISSUE TITLE
Use the new `AutoInject` attribute to remove all constructor injections

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#2155]
After developing the attribute and `Source Generator`, it is required to use this new feature in the projects.

**Comment by maryamhdr** [comment]
> After developing the attribute and `Source Generator`, it is required to use this new feature in the projects.

Which projects?
@msynk

**Comment by msynk** [comment]
@maryamhdr 
I think all projects?
@ysmoradi

**Comment by ysmoradi** [comment]
> @maryamhdr I think all projects? @ysmoradi

Yes, `Components Playground`, `Todo Template`, and even `Bit Platform Web Site`
Both Backend and frontend (Including razor files)

**Comment by maryamhdr** [comment]
> > @maryamhdr I think all projects? @ysmoradi
> 
> Yes, `Components Playground`, `Todo Template`, and even `Bit Platform Web Site` Both Backend and frontend (Including razor files)

So isn't it better to submit separate issues for each project?
@ysmoradi @msynk

**Comment by msynk** [comment]
@maryamhdr 
ok, I'm closing this one and will submit new ones for each project.
