### ISSUE TITLE
Sigup without check the privacy police

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2158]
On the  SignUp page without checking "I agree to the Bit police", I could post the form to the server by pressing the Enter key.

**Comment by msynk** [comment]
@maryamhdr 
I think this is a valid issue, we need to try to validate the form before sending the request.

**Comment by maryamhdr** [comment]
> @maryamhdr I think this is a valid issue, we need to try to validate the form before sending the request.

I think so, let me check it.
