### ISSUE TITLE
Update the `footer` content of the `TodoTemplate` project 

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2169]
- [x] The email address must be replaced with [info@bitplatform.dev](mailto:info@bitplatform.dev).
- [x] The social links must get these values:
  - Twitter: [https://twitter.com/bitplatformhq](https://twitter.com/bitplatformhq)
  - LinkedIn: [https://www.linkedin.com/company/bit-foundation](https://www.linkedin.com/company/bit-foundation)
  - YouTube: [https://www.youtube.com/channel/UCtk33NQ91f3GOJG0HAdkdog](https://www.youtube.com/channel/UCtk33NQ91f3GOJG0HAdkdog)
  - GitHub: [https://github.com/bitfoundation/bitplatform](https://github.com/bitfoundation/bitplatform)

- [x] Replace `Copyright © 2022 Bit Platform. All Rights Reserved` with `Made with ♥ using bit platform!`.

![freesnippingtool com_capture_20220608215122](https://user-images.githubusercontent.com/48528003/172698592-31d87085-dee4-4264-99c1-21b77152fbb1.png)

**Comment by ysmoradi** [comment]
Please use info@bitplatform.dev
