### ISSUE TITLE
The company logo in the confirmation email does not show

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2171]
![167682839-cdc3f9a4-6189-45e7-9a89-c7ad7de9e8f3](https://user-images.githubusercontent.com/62190682/173258492-747d4fe6-9b16-46c9-b04d-cb7ff87301d7.png)

- Based on R&D in [1994](https://github.com/bitfoundation/bitplatform/issues/1994), we need to remove the `IServer` interface from the project.
- In the `ConfirmationEmail` page, We must send the logo URL address to the client, like the email address (get server address from HttpContext)

**Comment by msynk** [comment]
what is this?
@ysmoradi 
@maryamhdr

**Comment by msynk** [comment]
hmm, 
I think we can use the previous issue to handle this problem since the only usage of the IServer is for the URL of the company logo? and use my suggestion (base64 string) to resolve that issue completely.
@ysmoradi 
@maryamhdr
