### ISSUE TITLE
`BitDatePicker` component label style issue

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2179]
The styles of the `BitDatePicker` component label are different from the FluentUI.
They are expected to be like this:

![freesnippingtool com_capture_20220611003301](https://user-images.githubusercontent.com/48528003/173142566-dbfbdca6-4683-42b7-bcb9-cc201a690a74.png)

**Comment by msynk** [comment]
@maryamhdr 
plz do not introduce multiple issues in 1 single issue. so plz separate the issues mentioned in this issue.

**Comment by maryamhdr** [comment]
> @maryamhdr plz do not introduce multiple issues in 1 single issue. so plz separate the issues mentioned in this issue.

Done sir :)

**Comment by ysmoradi** [comment]
Test message for GitHub notification system in Microsoft teams!

**Comment by ysmoradi** [comment]
> Test message for GitHub notification system in Microsoft teams!

2
