### ISSUE TITLE
Incorrect paddings of the white form in the `Todo` page of the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2180]
As shown in the following images, the paddings in the white form are not set correctly:

| **Current State** | **Expected State** |
|--------|--------|
|   ![freesnippingtool com_capture_20220608231242](https://user-images.githubusercontent.com/48528003/173144667-c0aae409-9afc-4d58-8cac-9dff1869becd.png) |    ![freesnippingtool com_capture_20220608233212](https://user-images.githubusercontent.com/48528003/173144751-884cf38b-d814-4965-a999-551c3be0f792.png) |

**Comment by msynk** [comment]
I don't understand what is the issue. could you plz provide more information?

**Comment by ysmoradi** [comment]
The same question
But, as far as I can see, the expected one, has a few Todo items, but the wrong one is empty 😅

**Comment by maryamhdr** [comment]
> I don't understand what is the issue. could you plz provide more information?

I updated the issue :)
Does it make sense now?

**Comment by maryamhdr** [comment]
> The same question But, as far as I can see, the expected one, has a few Todo items, but the wrong one is empty 😅

LOL

**Comment by msynk** [comment]
> > I don't understand what is the issue. could you plz provide more information?
> 
> I updated the issue :) Does it make sense now?

Actually, it was clear for me even before new changes 😁
but for an unbiased person, it still is not clear enough. I think adding some notations on images can help a lot.
