### ISSUE TITLE
Email text field Issue on the `Sign-Up` & `Sign-In` & `Forgot Password` Pages

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitplatform#2195]
In the `TodoTemplate` project, it is laborious when you try to give your email address on mobile.
It starts with a capital case character and doesn't include the @ character, and more awfully when you enter a dot it will include a space after that and again starts with a capital letter.

**Comment by msynk** [comment]
I think we can resolve this issue by adding the type=email on the input fields on these pages.
