### ISSUE TITLE
Incorrect background color of the `WebView` component for the Blazor hybrid mode in the TodoTemplate project

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitplatform#2250]
Currently, the background color of the WebView component is white (default color) which should be changed to `#0D2960` based on the design.

**Comment by msynk** [comment]
@ysmoradi 
why did you open this issue?
it's PR is merged, you shouldn't work on it anymore.

**Comment by msynk** [comment]
Since the PR is merged, I'm closing this issue.
