### ISSUE TITLE
Incorrect position of the CSS classes in the `BitDatePicker` component style file

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2272]
All of the CSS classes which have not the `-fluent` suffix must come inside the root element class which consists of a `-fluent` suffix.
For example, the `.bit-dtp-field-grp` class shown in the image below, has some styles that are for the Fluent design system like `border: rem(1px) solid $Grey130;`. So this class should be positioned inside the `.bit-dtp-fluent` class.

![freesnippingtool com_capture_20220626142337](https://user-images.githubusercontent.com/48528003/175809015-e33a4170-937c-419a-83e6-f6d3e2776c7e.png)

**Comment by msynk** [comment]
this is outdated, so I'm closing this issue.
