### ISSUE TITLE
`AutoInject` does not support `Generic` classes

### ISSUE THREAD

**Issue by mohabbati** [bitfoundation/bitplatform#2300]
When you try to add `AutoInject` in a `Generic` class then the Source Generator generates a `Non-Generic` class.

For instance, `BitNumericTextField` is a `Generic` class:
```C#
public partial class BitNumericTextField<TValue>
{
    //
}
````

The result of the Source Generator is:

```C#
public partial class BitNumericTextField
{        
    [Inject]
    [EditorBrowsable(EditorBrowsableState.Never)]
    private Microsoft.JSInterop.IJSRuntime ____JsRuntime { get => _jsRuntime; set => _jsRuntime = value; }
}
```

**Comment by ysmoradi** [comment]
We've finished working on the issue. You can try it in the upcoming pre-release. We'll let you know when the pre-release becomes ready. @mohabbati

**Comment by maryamhdr** [comment]
The pre-release has been published. Please give it a try and give feedback @mohabbati
