### ISSUE TITLE
Incorrent Icons used in the `BitDataGrid`

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#2363]
The icons used in the `BitDataGrid` component is not based on the BitBlazorUI design and should be replaced with appropriate icons from the fabric fluent icons.

**Comment by ysmoradi** [comment]
https://github.com/bitfoundation/bitplatform/issues/2324 ? @msynk

**Comment by msynk** [comment]
#2324 needs to be closed. it is explaining multiple un-related problems in 1 issue

**Comment by ysmoradi** [comment]
> #2324 needs to be closed. it is explaining multiple un-related problems in 1 issue @ysmoradi

)":

**Comment by msynk** [comment]
ok, I'm closing this one and work on #2324
just for you @ysmoradi
