### ISSUE TITLE
`Bit.BlazorUI.SourceGenerators` & `Bit.SourceGenerators` have conflicts when both referenced in the same project

### ISSUE THREAD

**Issue by milad-karimifard** [bitfoundation/bitplatform#2372]
Currently, when `Bit.BlazorUI.SourceGenerators` & `Bit.SourceGenerators` has referenced the same project, a conflict happens. the reason for this issue is both contain `BlazorSetParametersSourceGenerator`

**Comment by ysmoradi** [comment]
In which project have these two has referenced side by side? @milad-karimifard

**Comment by milad-karimifard** [comment]
Currently not, but when replacing standard injection with `AutoInject` on `Bit.BlazorUI`, it will happen.

**Comment by ysmoradi** [comment]
It's not a public issue that customers will face someday
Let's disable one of those source generators in our project
https://stackoverflow.com/a/66130446/2720104

**Comment by ysmoradi** [comment]
The main benefit of AutoInject is in our template projects, we can also ignore using that in Blazor UI components.
