### ISSUE TITLE
The presence of unknown character in the pages of the `Playground` project

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2373]
<img width="657" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/177048394-a7794a33-41cd-4c72-86f8-b3bcf17c4c94.png">

This is the `Get Started` page. But I think we should look for it in the whole project.

**Comment by ysmoradi** [comment]
Maybe the font that we've has nothing for `'` charecter

**Comment by sajadkardel** [comment]
<img width="744" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/177048876-67226ec1-06a0-4ce7-8e26-2a2b675f7a64.png">

It's in the code. @ysmoradi

**Comment by msynk** [comment]
somehow it was replaced in the renaming PR:
![image](https://user-images.githubusercontent.com/6169846/177075501-f0fda6bf-7566-4e15-a922-157c8842af24.png)
