### ISSUE TITLE
All dates are disabled when the default `BitDatePicker` value is smaller/bigger than the `Min/Max` date value

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2382]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62190682/177130231-e258009b-e9b2-4052-985a-b4aa505abac3.png)
<img width="680" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/177130464-46071c69-160f-4bd0-af42-42c5a0492bc9.png">
<img width="296" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/177130740-18c935b6-e42d-43ed-bd89-20ef32ef0cd3.png">

The Min date value is `DateTime.Now`
selectedDate value is `new DateTime(2020, 1, 17)`
In this case, the component should not be completely disabled

**Comment by maryamhdr** [comment]
The pre-release has been published. Please give it a try and give feedback. @mohabbati @sajadkardel
