### ISSUE TITLE
Header style is not defined correctly by using anchors in getting started in `Bit.Platform.webSite`.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#2398]
Header is shown like this
![image](https://user-images.githubusercontent.com/23101977/177157625-9d545bac-47ef-492c-8369-e15766680ea8.png)
rather than
![image](https://user-images.githubusercontent.com/23101977/177172706-d1b02e26-5e49-438e-8090-7dfead955e17.png)

by using anchors .

**Comment by maryamhdr** [comment]
Because the design of the header is gonna be changed, this issue is not valid anymore.
