### ISSUE TITLE
Add a `side-rail` for getting started in the `Bit.Platform.WebSite`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#2399]
https://www.figma.com/file/2997zoEMd4fhX9e912KIKr/bit-Platform?node-id=0%3A1

**Comment by maryamhdr** [comment]
> https://www.figma.com/file/2997zoEMd4fhX9e912KIKr/bit-Platform?node-id=0%3A1

plz provide an appropriate description for this issue
