### ISSUE TITLE
The problem in the TodoTemplate document

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitplatform#2403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The project context name is not TodoTemplateDbContext. It's AppDbContext.

![image](https://user-images.githubusercontent.com/45947371/177266623-146785e8-2693-40d0-a13b-42d56ec6224d.png)

![image](https://user-images.githubusercontent.com/45947371/177266683-0cf48d8c-0aee-4c9d-b888-2064f3e7b5ae.png)

**Comment by MeysamBahadori** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by MeysamBahadori** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
@hamedhajiloo

**Comment by ysmoradi** [comment]
The pre-release has been published. Please give it a try and give feedback

**Comment by hamedhajiloo** [comment]
That was Ok. Thank you.
