### ISSUE TITLE
Save the version of the template installed in the project.

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitplatform#2408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It seems that you should save the version of each template that is installed and used in the projects somewhere so that the problems of the projects that use the template can be checked.

### Describe the solution you'd like

I have no idea where to save this version, but for example, we can write it somewhere like above the program class and indicate that that line should not be deleted for future checks. Or, create a file with CodeGenerator and write it in it.

**Comment by msynk** [comment]
the template version is the same as the other bit projects version referenced in the template itself. for example the `Bit.SourceGenerators` or `Bit.CodeAnalyzers`

**Comment by ysmoradi** [comment]
No, the customer can update NuGet packages later and we can't find out which version of bit to do template was responsible for creating a project that the customer is facing an issue with. @msynk

**Comment by msynk** [comment]
hmmm, in this case the git history can help then :)

**Comment by hamedhajiloo** [comment]
I think that in a real situation if a problem occurs, it would be much easier to tell the user to go and see what version is used than to tell go check the Git history.

**Comment by msynk** [comment]
@ysmoradi 
@hamedhajiloo 
not really, this version also can be easily changed/removed by the developer, so eventually, you need to check the history.
I'm not against putting a comment or label or something somewhere in the template, I have significant doubt that this will help more than the git history check.

**Comment by ysmoradi** [comment]
Those are very simple project templates that no hassle is expected in them

**Comment by MeysamBahadori** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready. @hamedhajiloo

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.

**Comment by hamedhajiloo** [comment]
> The pre-release has been published. Please give it a try and give feedback.

What did you do about it? What should I check? @msynk

**Comment by msynk** [comment]
@hamedhajiloo 
please check the PR that has resolved this issue.
it's been shown in the history of this issue (look above 😀)
