### ISSUE TITLE
Uploading image fails in the `EditProfile` page of the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2416]
I'm trying to upload an image for my profile on the `EditProfile` page in Linux azure app service but I'm always getting the following error message:
`An error occurred while uploading file.`
I tried some different photos but still, get the same error. Here is a photo that shows the error message:

![image](https://user-images.githubusercontent.com/6169846/177783810-82f0dc28-f69b-4fec-9c42-e8def6d0f9b4.png)

**Comment by maryamhdr** [comment]
@msynk @ysmoradi 
Any ideas about this issue?!

**Comment by ysmoradi** [comment]
I'm releasing Android version of the components playground, could you please check that too so we can see if the uploader works properly on mobile or not?

**Comment by maryamhdr** [comment]
> I'm releasing Android version of the components playground, could you please check that too so we can see if the uploader works properly on mobile or not?

Sure...I'm on it!

**Comment by msynk** [comment]
![image](https://user-images.githubusercontent.com/6169846/177775528-c35bfea3-8f89-4c99-aa33-e434412e8971.png)

**Comment by maryamhdr** [comment]
> it's not just the android app
> 
> ![image](https://user-images.githubusercontent.com/6169846/177775528-c35bfea3-8f89-4c99-aa33-e434412e8971.png)

So could you update the issue plz?
