### ISSUE TITLE
Update the list of components on the home page of the  Bit `BlazorUI` demo project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2459]
There is a section named `Components` on the home page of the Bit `BlazorUI` demo project which presents a list of `Bit.BlazorUI` components. Based on the last changes, this list must be updated and the newly developed components must be added to the list.

**Comment by msynk** [comment]
this issue is handled in an unrelated PR (#2583) 🤦‍♂️🤦‍♂️🤦‍♂️
