### ISSUE TITLE
The sign up button gets enabled style while there is some invalid field in the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2488]
Here is the scenario in which I saw the bug:
I entered the sign-up page and filled all the fields, then checked the privacy checkbox. After these, the sign-in button became enabled. 
Then I removed some characters from the password/email...But the styles of the sign-up button still remained enabled.
Notice that even in this state, the sign-up button didn't work and the sign-up request hadn't been sent.

![freesnippingtool com_capture_20220712141827](https://user-images.githubusercontent.com/48528003/178466591-0d46f99b-595d-4989-9ca3-faffaaa3bfb4.png)
![freesnippingtool com_capture_20220712142724](https://user-images.githubusercontent.com/48528003/178466598-9336974c-f99e-42bc-8800-7d448baa0d60.png)
![freesnippingtool com_capture_20220712142802](https://user-images.githubusercontent.com/48528003/178466600-fa37f364-7320-48fa-a872-c3a00d12f1e9.png)

**Comment by msynk** [comment]
After investigation, I've found that this issue is not valid, so I'm closing it.
