### ISSUE TITLE
The submit button gets enabled style while there is an invalid field in the forget password page of the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2492]
Here is the scenario in which I saw the bug:
I entered the forget password page and filled the email field. After that, the submit button became enabled.
Then I removed some characters from the email...But the styles of the button still remained enabled.
Notice that even in this state, the submit button didn't work and the reset password request hadn't been sent.

![freesnippingtool com_capture_20220712145721](https://user-images.githubusercontent.com/48528003/178473820-59e32dd5-e285-4499-9e6a-e1b84636127a.png)

**Comment by msynk** [comment]
After investigation, I've found that this issue is not valid, so I'm closing it.
