### ISSUE TITLE
The file .gitignore is created in the wrong location when creating a project from TodoTemplate with Visual Studio.

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2493]
The file .gitignore is created in the wrong location when creating a project from TodoTemplate with Visual Studio, and causes git doesn't ignore some files like .vs, etc.

- when checking the "Place solution and project in the same directory checkbox" it's ok
- if create with the dotnet new command it's ok

**Comment by maryamhdr** [comment]
This issue is not valid anymore. So, I close it.
