### ISSUE TITLE
The button gets enabled style while there is some invalid field in the reset password page of the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2494]
Here is the scenario in which I saw the bug:
I entered the reset password page via the reset link and filled all the fields. After that, the button became enabled.
Then I removed some characters from the fields...But the styles of the button still remained enabled.
Notice that even in this state, the button didn't work and the reset password request hadn't been sent.

![freesnippingtool com_capture_20220712150237](https://user-images.githubusercontent.com/48528003/178477284-5d5b429d-19c8-4be6-bc64-2af2550297ab.png)

**Comment by msynk** [comment]
After investigation, I've found that this issue is not valid, so I'm closing it.
