### ISSUE TITLE
Add a custom action to the `Persona` component

### ISSUE THREAD

**Issue by saleh-ghezelbash** [bitfoundation/bitplatform#2510]
It would be better if it was possible to add or change an image or font icon to the component's status section.
For example, a button to change the user's profile picture.

![Capture](https://user-images.githubusercontent.com/80601183/178683449-49093176-ab51-4e46-9021-5a8c21c6af87.PNG)

**Comment by maryamhdr** [comment]
@saleh-ghezelbash 
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by maryamhdr** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

@saleh-ghezelbash

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
