### ISSUE TITLE
Problem with change namespace of AutoInject attribute

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#2517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We work in a `Blazor` project that uses `BitFaramework `and we changed the namespace of the `AutoInject `attribute, suddenly we got an error that said it couldn't be injected classes we expected.
![image_2022-07-13_13-53-48](https://user-images.githubusercontent.com/27281206/178787636-8a32d02d-2959-4bd3-840a-e647c3094bc5.png)
After renaming back the `AutoInject `attribute namespace to `Microsoft.Extensions.DependencyInjection`, it works perfectly like before.

### Expected Behavior

We expected the classes we inject in services must be injected where we need them but it not injected any of them,

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/27281206/178788713-d653ef38-36a0-41c1-b1ea-c134256f16e0.png)

### .NET Version

6.0.400

**Comment by msynk** [comment]
you're not supposed to change the AutoInject namespace or name. the full name of the attribute class should be exactly this:
`Microsoft.Extensions.DependencyInjection.AutoInjectAttribute`

**Comment by hootanht** [comment]
> you're not supposed to change the AutoInject namespace or name. the full name of the attribute class should be exactly this: `Microsoft.Extensions.DependencyInjection.AutoInjectAttribute`

But when we use the `Namespace Sync` feature in visual studio, it changes the namespace.  
![What's new in .NET Productivity with Visual Studio 2022 - Visual Studio Blog](https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2021/12/sync-namespaces-dark.png)

**Comment by msynk** [comment]
simply don't use it on this specific class 😉

**Comment by hootanht** [comment]
> simply don't use it on this specific class 😉

alright thanks dear Saleh🌹

**Comment by ysmoradi** [comment]
We could simply search for type name AutoInjectAttribute instead of its fullname
Such an exception is hard to troubleshoot and I'd recommend changing the approch
@msynk
What do you think?

**Comment by msynk** [comment]
@ysmoradi 
yeah, it's possible.

@hootanht 
I suggest submitting a new issue to request this new feature.

**Comment by ysmoradi** [comment]
He can simply submit PR for this too @hootanht
