### ISSUE TITLE
The title of the email page did not change in the project I built based on `TodoTemplate` project

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2520]
<img width="939" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/178827848-43ea3b53-29c6-485c-aee3-97e04abc0f6a.png">

My project name is `BTT`

**Comment by msynk** [comment]
@sajadkardel 
did you use the latest version of the TodoTemplate? it's 2.0.0-pre-03
I believe it was fixed in the last release

**Comment by sajadkardel** [comment]
<img width="882" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/178951192-47a6bf47-98d8-4950-b61b-79c099d25b77.png">

`2.0.0-pre-03` :)
