### ISSUE TITLE
The logo photo is not shown on the email page of the project that I built based on `TodoTemplate` project

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2521]
<img width="837" alt="Untitled - Copy" src="https://user-images.githubusercontent.com/62190682/178828290-4ee47545-98ee-4057-a3f7-834b1561c11c.png">

**Comment by msynk** [comment]
@sajadkardel 
based on the content of the email, I believe it's not the latest version of the TodoTemplate.
please test it with the latest pre-release version (2.0.0-pre-03)

**Comment by ysmoradi** [comment]
We need another pre-release
I believe this issue has been fixed already and only a pre-release is required to make it work
Just move icon.png from Resources to wwwroot/images in Api project

**Comment by sajadkardel** [comment]
I checked this and it doesn't seem to be a problem. As a result, I close this.
