### ISSUE TITLE
Existence of the `IsInEditMode` parameter in the Api input of the `TodoTemplate` project

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2522]
<img width="364" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/178999070-af8300e2-e538-426b-bd39-d7a6ec53c16d.png">

The `IsInEditMode` parameter in the `TodoItemDto`, is only for the razor page and shouldn't exist in Api input.
(There is an example of this in UserDto)

**Comment by msynk** [comment]
now YES :)
