### ISSUE TITLE
the `AutoInject` attribute does not work with generic type fields

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2523]
I created a project based on TodoTemplate and implemented the generic repository pattern in it.
I wrote this as a field in the controller with the `AutoInject` property:

<img width="435" alt="Untitled3" src="https://user-images.githubusercontent.com/62190682/178830155-f2cb0daf-1cd3-4e4a-8b34-ca9d915bbd16.png">

Result:

<img width="370" alt="Untitled4" src="https://user-images.githubusercontent.com/62190682/178830247-7e1163ce-595b-49f2-a0f7-03df6c45caae.png">

I did the same with the Constructor Injection method and everything worked fine.

**Comment by sajadkardel** [comment]
[Bit-Template-Tuning](https://github.com/sajadkardel/Bit-Template-Tuning)
here you are. @msynk

**Comment by msynk** [comment]
@sajadkardel 
I have no problem building your source code.

I've changed the TodoController back to using AutoInject btw.

**Comment by sajadkardel** [comment]
<img width="732" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/178833524-9f2d5f55-e4ed-427f-8b25-e78b2309f429.png">

I checked here it seems to be correct. @msynk

**Comment by msynk** [comment]
so what is the problem here?

**Comment by sajadkardel** [comment]
Not. Probably my problem was from another dependency. We can close this.
