### ISSUE TITLE
`BitSlider` component UI issues

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2524]
Test on the new Blazor project
Chrom, firefox, edge
- Vertical Range Slider
![screenshot](https://user-images.githubusercontent.com/107020266/178903725-66ca86b7-2d22-4cda-be2b-2510712886a5.png)

`<BitSlider Label="Vertical Range Slider"
           Min="1"
           Max="10"
           Step="1"
           DefaultUpperValue="8"
           DefaultLowerValue="2"
           IsRanged="true"
           IsVertical="true" />`

- Middle indicator on wrong place
![image](https://user-images.githubusercontent.com/107020266/178904332-05eca717-8538-44d2-86de-a4c471f4625e.png)
`<BitSlider Label="Origin From Zero"
           Min="-5"
           Max="15"
           Step="1"
           DefaultValue="5"
           IsVertical="true"
           IsOriginFromZero="true" />`

- Also it has some problems with firefox

**Comment by msynk** [comment]
this issue is not valid anymore
