### ISSUE TITLE
the Component demo page examples issue

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2553]
On the components demo page 
- Component demo samples code font size on mid-screen (for example by with 800) is small and unreadable.
- On the code view on the component's sample  the copy source button doesn't copy the code correctly and doesn't fetch the @code block

**Comment by msynk** [comment]
@MeysamBahadori 
again, multiple problems in 1 issue.
please separate them.

**Comment by MeysamBahadori** [comment]
It was created separately for each issue

**Comment by maryamhdr** [comment]
This issue is separated into #2573 and #2574 so, I'll close it.

**Comment by maryamhdr** [comment]
This issue is separated into #2573 and #2574 so, I'll close it.
