### ISSUE TITLE
Incorrect label for the `Custom Label` sample of the `BitToggle` component demo page

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2555]
The first sample is not an `Inline` label, but the label itself contains the misleading Inline word:

   ![image](https://user-images.githubusercontent.com/107020266/179176256-33828d31-935b-4dba-a02e-0eab7fe2c8f6.png)

**Comment by msynk** [comment]
What is the issue here?
I'm not seeing any issues 🧐

**Comment by MeysamBahadori** [comment]
In the first example label, "Inline" is written incorrectly, when it is not

**Comment by msynk** [comment]
oh I see, the `Inline` is not written incorrectly but the label itself is misleading.
the label should be something like this: `Custom Label` for non-inline sample.
