### ISSUE TITLE
The font size on mid-screen size issue in the demo samples codes of the Bit `BlazorUI` demo project

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2573]
Component demo samples code font size on mid-screen (for example by with 800) is small and unreadable.
There is no problem with larger and smaller screen sizes.

**Comment by msynk** [comment]
@MeysamBahadori 
could you plz provide an image of the issue?

**Comment by MeysamBahadori** [comment]
width 800
![image](https://user-images.githubusercontent.com/107020266/179425001-1e25f0f5-7a67-46c0-97e5-ac99701d6593.png)

width 530
![image](https://user-images.githubusercontent.com/107020266/179425078-09a9b362-78fc-4a2f-9d40-0bb2b39ba9e1.png)
