### ISSUE TITLE
Missing `@code` phrase in the copied content of the source code sample of the BlazorUI component demo pages

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2574]
On the code view on the component's sample page, the copy source button doesn't copy the code correctly and the `@code` phrase is missing in samples with both HTML and C# content.

**Comment by msynk** [comment]
I've tested this feature and the copy feature works fine for me.
what is the exact problem here?

**Comment by MeysamBahadori** [comment]
when you click on the copy source button and paste it to another place,
 "@code{}" missed
for example 
```
<BitCheckbox @bind-Value="IsCheckBoxChecked">Basic Checkbox</BitCheckbox>

@code{
private bool IsCheckBoxChecked = false;
}
```
converted to
```
<BitCheckbox @bind-Value="IsCheckBoxChecked">Basic Checkbox</BitCheckbox>

private bool IsCheckBoxChecked = false;

```

**Comment by msynk** [comment]
It's not the issue of the copy feature, the demo page itself has a missing part in the code samples provided for the ComponentExampleBox component.
plz provide more information about which demo pages have this issue.

**Comment by msynk** [comment]
![image](https://user-images.githubusercontent.com/6169846/179428157-f54d724c-f379-47b8-8a7e-0c4a0b374586.png)
