### ISSUE TITLE
`ResetPassword` Email template doesn't generate and throw exception

### ISSUE THREAD

**Issue by milad-karimifard** [bitfoundation/bitplatform#2580]
Currently, when trying to reset the password in `TodoTemplate`, an exception is raised and the operation failed.

Exception message: 

> TodoTemplate.Shared.Exceptions.UnknownException: Failed to compile generated Razor template:
> - (58:34) The type or namespace name 'Uri' could not be found (are you missing a using directive or an assembly reference?)

**Comment by maryamhdr** [comment]
@msynk 
Could you investigate this issue, plz?
