### ISSUE TITLE
The `BitFileUpload` component's upload percentage issue

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2614]
It shows 100% progress before the file is sent
![image](https://user-images.githubusercontent.com/107020266/179683158-93a753a9-0fc7-40c2-a5fb-c31c959e8930.png)

**Comment by maryamhdr** [comment]
Can you explain the scenario in which this issue takes place?
@MeysamBahadori

**Comment by MeysamBahadori** [comment]
[file-Upload](https://components.bitplatform.dev/components/file-upload#example1)

**Comment by msynk** [comment]
@MeysamBahadori 
please explain more about the issue and how it can be reproduced
