### ISSUE TITLE
Inappropriate image style when the image source is unavailable in the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2688]
When the alt text of an `img` tag displays, it doesn't look good and needs to be styled.
![freesnippingtool com_capture_20220723123643](https://user-images.githubusercontent.com/48528003/180596679-431baa89-76a6-4bb7-b9d4-e45f7640756f.png)
![freesnippingtool com_capture_20220723123810](https://user-images.githubusercontent.com/48528003/180596681-b19d9968-18f3-4195-a07a-c1427a120f69.png)

**Comment by msynk** [comment]
it's not the alt problem.
the `img` element's `onerror` event should be handled and in case of an error, a specific UI should be rendered instead of the default behavior which is showing this inappropriate view.
