### ISSUE TITLE
Scrollbar hides in the todo list of the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2691]
The scrollbar of the to-do list on the `Todo` page is hidden, so if there are many items below the current items, the users can't see the scrollbar and it causes a bad user experience.
![freesnippingtool com_capture_20220723130944](https://user-images.githubusercontent.com/48528003/180597626-4d077aa3-8fce-4c4f-8eea-9ee85264fd49.png)

![freesnippingtool com_capture_20220723130931](https://user-images.githubusercontent.com/48528003/180597625-cc4f7e9f-e67c-448e-ac17-65a45e570d45.png)

**Comment by msynk** [comment]
it is not hidden:
![image](https://user-images.githubusercontent.com/6169846/180597977-554c06d6-278b-457e-9b79-9ea0ce4f48d1.png)

it's the feature of the mobile that is simulated correctly in the responsive view of the devtools.

**Comment by maryamhdr** [comment]
This issue is not valid.
