### ISSUE TITLE
Sorting based on color issue in the categories `BitDataGrid` of the `AdminPanel` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#2719]
To display the list of categories, we have used a `BitDataGrid` component in the `AdminPanel` project. Here, there is an issue in sorting the data based on the `color` column which needs to be resolved.

**Comment by MeysamBahadori** [comment]
We use the following method to get the column sorting rule, but this method does not work for columns of the type `Bit DataGridTemplateColumn`. And the color column is also of this type

Method  GetSortByProperties() in BitDataGridItemsProviderRequest<TGridItem> structure
[BitDataGridItemsProviderRequest](https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Bit.BlazorUI/Components/DataGrid/ItemsProvider/BitDataGridItemsProviderRequest.cs)

@msynk

**Comment by ysmoradi** [comment]
Good, I'd recommend disabling sort functionality of that column at least until we fix the root cause

**Comment by msynk** [comment]
I've submitted a new issue for disabling this feature (#2771)

**Comment by msynk** [comment]
this issue is not valid anymore
