### ISSUE TITLE
BlazorUI component demo chart page issue

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2747]
In the Chart demo page when switching between code and example view the Chart doesn't show again

**Comment by MeysamBahadori** [comment]
I suggest replacing the current code with the following code or making a separate chart display component

in the \[ComponentExampleBox\](https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Components/ComponentExampleBox.razor) use \*\*hidden="@showCode"\*\* instead of \*\*@if (!showCode) else\*\*  
\`\`\`  
\<div class="box-content">  
       \<div class="example-container" hidden="@showCode">  
           @ExamplePreview  
       \</div>  
       \<div hidden="@(!showCode)">  
           \<BitIconButton Class="com-example-box-copy-btn"  
                          OnClick=CopyCodeToClipboard  
                          IconName="BitIconName.Copy"  
                          Title="Copy source">  
           \</BitIconButton>

           \<pre class="code">  
           \<code class="html">@HTMLSourceCode.Trim()\</code>

               @if (CSharpSourceCode.HasValue())  
               {  
               \<code class="csharp">  
           @code {@CSharpSourceCode.Trim().Replace("\\n", "\\n     ")  
           }\</code>  
               }  
            \</pre>  
       \</div>  
   \</div>  
\`\`\`

**Comment by msynk** [comment]
It's not a demo page issue, it's the issue of the `BitChart` component itself.
Although the solution you've suggested can be a simple workaround for this issue on the demo page

**Comment by msynk** [comment]
This issue is resolved, so I'm closing it.
