### ISSUE TITLE
The confirm email address page issue

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#2752]
In the case that the user has SignUp but an email has not been sent to her/him if the user immediately clicks on the resend button, a wrong error text will be shown to her/him.

![image](https://user-images.githubusercontent.com/107020266/180781558-4480f5b8-1f16-4c3f-b611-df8988b62ccd.png)

**Comment by msynk** [comment]
I don't think that's an issue. It's the intended behavior.

**Comment by ysmoradi** [comment]
That's fine.
