### ISSUE TITLE
The close button mismatch in the `BitMessageBar` component during horizontal scrolling

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2767]
<img width="945" alt="MessageBar" src="https://user-images.githubusercontent.com/62190682/181018371-ef9e9315-c016-4e73-b2fb-5a1eef4873ed.png">

On the `SignIn` page in the `TodoTemplate` project when a server error occurs, This error is displayed in `BitMessageBar`.
When a long text error occurs and the BitMessageBar scrolls horizontally, the close button is scrolled.

**Comment by msynk** [comment]
this issue is not valid anymore
