### ISSUE TITLE
Photos that are placed as links in the project are not shown in the mobile app

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2783]
**An example of a page that has these conditions:**

![e4f013be-4bdd-4885-b915-90f3fc9068b7](https://user-images.githubusercontent.com/62190682/181270585-a15c6d8b-ce92-45f1-a3b0-6e98c42375d0.jpg)

**Comment by ysmoradi** [comment]
This issue is not relevant anymore
