### ISSUE TITLE
The `OData` and `Virtualize` DataGrids are empty in the mobile app 

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2784]
![85a05e0f-a79b-4ef5-87bb-117a7478d85a](https://user-images.githubusercontent.com/62190682/181271294-a442cd94-a6e7-4805-95a0-bf8dabdf3085.jpg)

**Comment by MeysamBahadori** [comment]
the virtualization example of DataGrid work with VPN and has no problem

**Comment by msynk** [comment]
@sajadkardel 
could you plz confirm @MeysamBahadori 's comment? if so please close this issue with a comment.

**Comment by MeysamBahadori** [comment]
I tested it with VPN and it works, As for the OData example, I know that @ysmoradi  works on it.

**Comment by sajadkardel** [comment]
This issue has been checked and is still valid. @msynk

**Comment by ysmoradi** [comment]
Seems to be a linker issue, it works in debug mode, but doesn't work in release mode

**Comment by ysmoradi** [comment]
This issue is not relevant anymore
