### ISSUE TITLE
Interweaving the chart when Dataset is added too much

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2785]
With the addition of Dataset, the height of the chart decreases. This continues until the chart is no longer visible.
(It is visible at any size, only the number of clicks on the `Add Dataset` button will be different.)

![e8aa062c-bac9-43af-8530-018884617731](https://user-images.githubusercontent.com/62190682/181274159-daba71b6-7e17-4804-8bca-a72a0e1f3b31.jpg)

**Comment by MeysamBahadori** [comment]
This problem exists in the main demo of the Chartjs examples
[Vertical Bar Chart](https://www.chartjs.org/docs/latest/samples/bar/vertical.html#vertical-bar-chart)

## To solve this problem :
- the Chartjs has a legend property with the name of **maxHeight** which BitChart has not implemented
[Legend](https://www.chartjs.org/docs/latest/configuration/legend.html#legend)
And of course, using this solution the height of the Legend is limited and all of them don't show.
-  it can be possible to limit the number of Legends shown

- We can create a custom HTML legend using a plugin like ["this sample"](https://www.chartjs.org/docs/3.3.2/samples/legend/html.html#html-legend) 

@msynk

**Comment by msynk** [comment]
this issue is not important atm for us to work on. I'm removing it from the current sprint

**Comment by msynk** [comment]
not valid anymore
