### ISSUE TITLE
The exponential addition of values ​​when we click on one of the `BitBreadCrumb` items in the mobile app

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2788]
The correct dropdown value in the image below should be:

- Folder 2
- Folder 3

This is true the first time we enter this page. But if we click on one of the BreadCrumb items(for example `Folder 4`), every time we do this, the number of dropdown values ​​will be repeated.

one click:
- Folder 2
- Folder 3
- Folder 2
- Folder 3

two clicks:
- Folder 2
- Folder 3
- Folder 2
- Folder 3
- Folder 2
- Folder 3

**(Note that this is only the case on the mobile app and not on the web)**

![69ed9b96-2761-49f3-8b49-d61a0d8cd21b](https://user-images.githubusercontent.com/62190682/181281472-f49f306e-214d-470d-9574-ec1198f49e61.jpg)

**Comment by sajadkardel** [comment]
I think this is helpful: [Singleton vs Transient in Maui](https://www.youtube.com/watch?v=oC5zpEbwViE)

**Comment by msangtarash** [comment]
As I checked this does not happen anymore.
