### ISSUE TITLE
The dimensions in the items of the `BitCarousel` do not get updated after its container gets resized

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#2793]
The dimensions in the items of the `BitCarousel` do not get updated after its container gets resized

**Comment by mhrastegary77** [comment]
Facing the same issue :(

**Comment by mhrastegary77** [comment]
any workarounds on this? :(

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
