### ISSUE TITLE
Misspelling `HealthCheckSettings` in the template projects

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitplatform#2833]
There is a misspelling for `HealthCheckSettings` in template projects configurations as shown in the following image:

![image](https://user-images.githubusercontent.com/6169846/182019845-493cf602-fe9a-4084-a7df-f13ff51d9db0.png)

**Comment by msynk** [comment]
@Md23Mh could you please share where exactly is the problem?

**Comment by Md23Mh** [comment]
In appsettings we have "HealCheckSettings" instead of "HealthCheckSettings".

**Comment by msynk** [comment]
I've updated the issue description for it to be more clear.
