### ISSUE TITLE
Set spacing for item in `Bit Carousel`

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#2839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We can't set spacing between item in `Bit Carousel`.

### Describe the solution you'd like

We can have parameter for `Bit Carousel` to set the spacing between item.

**Comment by msynk** [comment]
@hootanht thanks for submitting this issue.

can't this issue be simply resolved with a little styling of the items?
for example:

```razor
<BitCarouselItem Class="item"><div>1</div></BitCarouselItem>
```

```css
::deep .item div {
    margin: 0 10px;
    background: red;
}
```

**Comment by hootanht** [comment]
> @hootanht thanks for submitting this issue.
> 
> can't this issue be simply resolved with a little styling of the items? for example:
> 
> ```
> <BitCarouselItem Class="item"><div>1</div></BitCarouselItem>
> ```
> 
> ```css
> ::deep .item div {
>     margin: 0 10px;
>     background: red;
> }
> ```

When we assign margin to `Bit Carousel` it affects the start item and end item in the list. we want to fix the first item and last item from the list.

![](https://user-images.githubusercontent.com/27281206/182186319-efa4e469-8f4c-4c11-9461-7f371081543c.png)

**Comment by msynk** [comment]
can't you exclude them with something like `:first-child` and `:last-child` ?
