### ISSUE TITLE
The text of the nav item does not fit in the item box of the `BitNav` component

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2853]
If the text is too long, it will go beyond the specified box and break.

<img width="318" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/182361777-838f22db-2374-4a50-b279-1ddc5d9c1e4e.png">

**Comment by msynk** [comment]
I'm not seeing such a thing:

![image](https://user-images.githubusercontent.com/6169846/182479073-9ed91888-92fc-4ac1-b354-b44c38399bb6.png)

**Comment by mohabbati** [comment]
And also it is ok for me:

![Screenshot 2022-08-03 120442](https://user-images.githubusercontent.com/13447649/182569892-c5c822a0-bf27-4c58-84f0-c2a3a370d3f9.png)

**Comment by sajadkardel** [comment]
So I close this issue 👍 @msynk @mohabbati
