### ISSUE TITLE
Incorrect the `BitNav` overridden CSS classes in the `bit platform` website

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2860]
some classes of the `BitNav` component have been overridden in the `Bit Platform` website project. The names of these classes have been changed in the `BitNav` component. So current, any name starting with `bit-nav-` in the `NavMenu.razor.scss` file is incorrect.

**Comment by msynk** [comment]
it needs to be mentioned that this should be taken care of after the next prerelease. for now it's fine.
