### ISSUE TITLE
The `BitDataGrid` component is not responsive enough and will be rendered incorrectly in small screens

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#2870]
![image](https://user-images.githubusercontent.com/23101977/182538596-1da1e23b-171b-4fbd-81d8-b74988239f04.png)

**Comment by sajadkardel** [comment]
I think this issue already exists(#2787). @msangtarash @msynk ??

**Comment by msynk** [comment]
@sajadkardel you are right.
but the image provided in issue #2787 is not a good one. could you plz update the image and use a better one? like the one in this issue.
I'm closing this issue since it's a duplicate of #2787
