### ISSUE TITLE
Blazor WASM Map Control with Dynamic Marker Manipulation

### ISSUE THREAD

**Issue by MarshalOfficial** [bitfoundation/bitplatform#2926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Yes, in blazor wasm this is a big challenge to show maps and also the creation of markers from business data.

### Describe the solution you'd like

A fully dynamic map control that handles different map providers such as Google, Open street map, Bing, etc.

### Additional context

![image](https://user-images.githubusercontent.com/8558078/183367157-1f08feb5-6517-42b7-bd1a-a62cf94a93d7.png)

**Comment by msynk** [comment]
@MarshalOfficial thanks for contacting us.
we are investigating this request and will soon come back to you with the results

**Comment by msynk** [comment]
not planned yet
