### ISSUE TITLE
Incorrect style in the `Loading` page

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2932]
![ScreenCapture_20220807224048388](https://user-images.githubusercontent.com/62190682/183420028-334db323-69b6-4b31-ab14-9e3f02d505c7.jpg)

**Comment by maryamhdr** [comment]
This issue is going to be fixed in #2900 :D

**Comment by msynk** [comment]
we are aware of this issue and it's being fixed, so I'm closing this issue.
