### ISSUE TITLE
Icon behavior issue in side rale in `Bit.Website.Platform` project

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#2953]
![image](https://user-images.githubusercontent.com/23101977/183883064-150cf7ef-fccf-43c4-9119-fbafb4f8d01f.png)

**Comment by sajadkardel** [comment]
This issue will be resolved in (#2860).

**Comment by msynk** [comment]
since this is a duplicate of #2860, I'm closing it.
