### ISSUE TITLE
Incorrect `@inherits` in the `BitToggleButton` component

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#2985]
We have defined a base class for input components that return value. this class name is `BitInputBase<value type>`.
Currently, the `BitToggleButton` component that returns a `bool` does not inherit from this class and its return value is handled by a parameter called `IsChecked`, which is against the rules.

**Comment by msynk** [comment]
Although you might be right, we need to discuss it further.
I can argue that this component is actually a button with a custom internal state and not an input element.

**Comment by msynk** [comment]
after some investigations, we concluded that this component is not an input element, so I'm closing this issue.
