### ISSUE TITLE
Incorrect rendering of component `BitBasicList`

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#3055]
In the `BitBasicList` component, if `Virtualize` is disabled, each item will be rendered in a `div` tag, which is not correct. For example, it is not possible to create rows of a table with this component.

**Comment by msynk** [comment]
@Cyrus-Sushiant 
did you check it with the FluentUI component too?

**Comment by Cyrus-Sushiant** [comment]
> @Cyrus-Sushiant 
> did you check it with the FluentUI component too?

Yes, this case is the same in FluentUI, but FluentUI adds a series of classes and attributes to each item and uses that div for this purpose.
