### ISSUE TITLE
Add a global callout handler for all the components that have the callout

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitplatform#3058]
currently, We have several components that have callout capabilities. Like the `BitBreadcrumb`, `BitSplitButton`, `BitDatePicker` and `BitDropDown`. The `TS` code of all these components is almost the same and we need to define only one TS class for all of them.

**Comment by msynk** [comment]
it is being resolved progressively in the current improvement phase, so I'm closing this one.
