### ISSUE TITLE
Misspelled `Sign Up` in both template projects

### ISSUE THREAD

**Issue by milad-karimifard** [bitfoundation/bitplatform#3167]
Currently, in some places of both templates, there is a typo for `Sign Up`

![image](https://user-images.githubusercontent.com/46561982/188261980-05cd7ea9-0c36-4d36-80b5-eaccfb0ea521.png)

![image](https://user-images.githubusercontent.com/46561982/188262002-fd135516-a227-49bc-85de-352c377c0a80.png)

**Comment by ysmoradi** [comment]
Could you please check the same for `todotemplate`?

**Comment by milad-karimifard** [comment]
> Could you please check the same for `todotemplate`?

I check this in the first place. the second photo is for `todotemplate`
