### ISSUE TITLE
improve ReadMe.md file

### ISSUE THREAD

**Issue by shh79** [bitfoundation/bitplatform#3168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Please add solution step by step in **ReadMe.md** file about "How to config bit framework API in **Angular/.Net** projects?".
we use **Bit framework API** in many projects without know how to config them and this informations can be very useful for us.
thanks !!!

**Comment by ysmoradi** [comment]
Could you please describe about bit features that are being consumed in your project + your project structure?

**Comment by ysmoradi** [comment]
Closed due to no response
