### ISSUE TITLE
Replace `Web Compiler 2022+` extention title and marketplace link with `Abstractions Sass Compiler` in `DevelopmentPrerequisitesPage`

### ISSUE THREAD

**Issue by mohabbati** [bitfoundation/bitplatform#3201]
**Web Compiler 2022+** extension replaced with **Abstractions Sass Compiler** in our project templates due to some limitations on other platforms. So we need to update the environment requirements in the documentation.

Marketplace link:
https://marketplace.visualstudio.com/items?itemName=AbstractionsAS.AbstractionsSassVisualStudioExtension

**Comment by ysmoradi** [comment]
I can't understand why this issue has no `high priority` label
We've released V4.1 stable which is not working with web compiler extension anymore!
@mohabbati
