### ISSUE TITLE
`BitToggleButton` icon is not matched with its text

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitplatform#3208]
The icon for the sample of toggle button in demo page doesn't match with the text; if it is muted and we aim to unmute then the icon should display muted state.

By the way these two buttons have the same reaction when I click on them (i.e., when I click on one the other changes a well), is this OK?

![image](https://user-images.githubusercontent.com/26743275/189545696-7eaf1d58-ea1e-4a04-bed0-f5ddfa7cb144.png)

**Comment by msynk** [comment]
this behavior is intended in this sample. but I agree that this is a little confusing. we need to improve this example at least by adding a description to explain the situation.
