### ISSUE TITLE
Button text not showing after clicking one of the buttons in `SplitButton` with `IsSticky` sample

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitplatform#3209]
When I select a button nothing appears in front of the label (clicked item):
![image](https://user-images.githubusercontent.com/26743275/189545944-3b615c17-6108-4ecf-ab4a-5d9f021b6713.png)

**Comment by Md23Mh** [comment]
Oops I should have clicked on it! So there is no issue but this has bad UX I suppose.

**Comment by Md23Mh** [comment]
![](https://user-images.githubusercontent.com/26743275/189546523-5fe9f738-df4b-41a0-b2ab-ecc9f1413f34.png)

The same issue persists with the next sample. Why do we need to click again on the selected button with IsSticky to trigger the event?

**Comment by msynk** [comment]
these behaviors are correct and intentional, but I agree that these might be a little confusing.
