### ISSUE TITLE
Clarify the functionalities of `BitCheckbox` samples in demo page

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitplatform#3210]
1. In the first sample group of `BitCheckBox` when I click on the second one it doesn't change. We need to add an explanation for these samples to clarify for the user that this sample is intentionally like this.
![image](https://user-images.githubusercontent.com/26743275/189546795-bb886a7d-5fa2-4721-930e-c0a767a50204.png)

2. The reversed sample also needs clarification:
![image](https://user-images.githubusercontent.com/26743275/190585500-384b8eb3-4032-424c-8668-c3d502bf1184.png)

3. When clicked on the first or the forth the two check boxes change the same, add more explanation to show that it is deliberate.
![image](https://user-images.githubusercontent.com/26743275/190589081-204a1fe3-06d2-44b4-b097-590fb1ee6f2c.png)

4. The button "Make Checkbox Indeterminate" has a very bad UX; it doesn't specify which button it is going to change. Please add more explanation to make it more clear or change the design.

5. When clicked on the second sample of indeterminate checkbox it doesn't change. Please add an explanation for this too.
![image](https://user-images.githubusercontent.com/26743275/190590433-55b9f54c-45aa-4612-a04f-c968d6fd9fb9.png)

**Comment by Md23Mh** [comment]
The same issue persists with the next sample group (reversed):  
 

![](https://user-images.githubusercontent.com/26743275/189546930-ba10a410-190a-49a4-ba9b-93242a71cc0a.png)

**Comment by sajadkardel** [comment]
this is resolved by [#3372] @msynk @Md23Mh
