### ISSUE TITLE
Customized Dropdown is opening in wrong position in small screens.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3251]
I checked it on iPhone but it is happening on android too.

![IMG_0230](https://user-images.githubusercontent.com/23101977/191686150-0e0a7728-e967-4078-b506-40b848885ceb.PNG)

**Comment by msangtarash** [comment]
![IMG_0255](https://user-images.githubusercontent.com/23101977/190902689-724971ce-fe92-4934-a0e5-ccd3d5c6b5f5.PNG)
we also have this issue with the date picker

**Comment by msynk** [comment]
This issue is resolved, so I'm closing it.
