### ISSUE TITLE
Scrolling issue in modals

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3260]
By scrolling modals content, it doesn't scroll 

![IMG_0240](https://user-images.githubusercontent.com/23101977/191684870-093287cf-9ec2-4bb7-a1b2-c393dd1af0ff.PNG)

**Comment by mhrastegari** [comment]
in fact behind of the modal will scroll :)

**Comment by msynk** [comment]
This issue is resolved, so I'm closing it.
