### ISSUE TITLE
Style issues in small screens in `BlazorUI`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3269]
- [ ] **`BitCarousel` demo page**

 
![IMG_0263](https://user-images.githubusercontent.com/23101977/191680756-50f33f72-e5a4-4c0a-805e-c06f17152b09.PNG)

- [ ] **`BitButton` demo page**

![190903197-166b29d3-b23f-4807-aa4b-89fcf1348b7a](https://user-images.githubusercontent.com/23101977/191697951-9da7c718-8ee6-4431-a9fe-a5eb00f9ac09.jpg)

- [ ] **`Parameters` sections**

![190903205-3f9a418d-0958-4a65-a3c2-ec5a0d532203](https://user-images.githubusercontent.com/23101977/191697846-f7977429-c6a1-408f-9cb1-e0d70c139cfc.jpg)

- [ ] **`BitCheckBox` demo page**

![check](https://user-images.githubusercontent.com/23101977/191714668-a606eb94-97fd-4981-8b8d-287f2f227dac.jpg)

![check2](https://user-images.githubusercontent.com/23101977/191714716-6f268cca-85aa-49e9-8051-29091b205ad8.jpg)

**Comment by mhrastegari** [comment]
This issue has been fixed in #4742

**Comment by msynk** [comment]
all of the problems in this issue is already fixed before, so I'm closing it.
