### ISSUE TITLE
Allow users to change global styles of all components at once

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#3338]
### Summary
Is it possible to have something like a style configurations file to allow users to change the AccentColor(the default blue color) of all components?
and even other things! like font family, text color and ...

**Comment by msynk** [comment]
We're investigating your issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by Kkalinovk** [comment]
Is there any update on the topic?

**Comment by msynk** [comment]
we are still investigating this issue. the result will be announced soon 😊

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
closed by #4436

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
