### ISSUE TITLE
'Datagrid' reload problem

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [bitfoundation/bitplatform#3363]
I installed admin project recently, when i run it on web Assembly mode in product page after adding & editing product datagrid doesnt update automaticly this just work after deleting product

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by ebrahimkhodadadi** [comment]
Can i solve this issue by my self in code?

**Comment by msynk** [comment]
this issue is approved.

**Comment by msynk** [comment]
why did you close this issue? it's not resolved yet. lets the PR be merged first plz.
I'm re-opening this issue.

**Comment by ebrahimkhodadadi** [comment]
OK tnx

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.

**Comment by ebrahimkhodadadi** [comment]
this issue solved in pre-release. Thanks
