### ISSUE TITLE
[WinUI] Change Todo template app default `TitleBar` background and foreground color

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#3379]
### Summary
The default TitleBar color of Windows version in MAUI is an ugly gray color, my suggest is set the TitleBar color to white.

### Screenshot
Before
![Screenshot 2022-10-18 013319](https://user-images.githubusercontent.com/42671084/196292987-f749460e-767d-4428-af49-c8de0b274e75.png)
After
![image](https://user-images.githubusercontent.com/42671084/196299784-07e1387d-ec9d-4e73-9748-122c12ba3b1e.png)

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
