### ISSUE TITLE
BitDateRangePicker Two-way binding does not work.

### ISSUE THREAD

**Issue by MeysamBahadori** [bitfoundation/bitplatform#3390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**BitDateRangePicker** Two-way binding does not work.

Also, I saw this problem on the demo page
[Demo Page](https://components.bitplatform.dev/components/date-range-picker#example8)

### .NET Version

6.0.400

### Anything else?

Bit.BlazorUI : 4.4.0-pre-01

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.

**Comment by MeysamBahadori** [comment]
Thanks for your responsible follow-up, the issue has been resolved.
