### ISSUE TITLE
[iOS] Change Todo template's `WebView` default background color

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#3409]
### Summary
Currently `BlazorWebView` for iOS uses `WKWebView` which has a default white background color.
My suggest is to set it to transparent.

**Comment by ysmoradi** [comment]
Could you please submit the same for AdminPanel? @mhrastegari

**Comment by mhrastegari** [comment]
Ok I'll reopen the issue till it gets merged.

**Comment by mhrastegari** [comment]
Done

**Comment by msynk** [comment]
plz don't submit new PRs for closed issues

**Comment by mhrastegari** [comment]
ok 👀

**Comment by mhrastegari** [comment]
should open a new one?
