### ISSUE TITLE
Change `BitDropDown` icon issue.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3422]
I want to change the icon in  `BitDropDown`

![image](https://user-images.githubusercontent.com/23101977/197391523-a54ab92a-859f-4708-ae8d-bcc95e369b84.png)

 to be able to implement 
 
![image](https://user-images.githubusercontent.com/23101977/197391562-9b656c99-80c4-41d9-9c51-3bac3efdcd5e.png)

but as the content of i is set in the razor I can't change it easily :|

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msangtarash** [comment]
Thank you for the changes :)
