### ISSUE TITLE
Fix issue page link in Github `Issue templates` (#3431)

### ISSUE THREAD

**Issue by taha-ghadirian** [bitfoundation/bitplatform#3431]
Hi, I found a problem in linking to github issues page on [Feature request issue template](https://github.com/bitfoundation/bitplatform/blob/develop/.github/ISSUE_TEMPLATE/feature_request.yml), the checkbox should redirect user to [Bit platform issues](https://github.com/bitfoundation/bitplatform/issues) not microsoft dotnet issues.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.

**Comment by taha-ghadirian** [comment]
> The pre-release has been published. Please give it a try and give feedback.

Thanks for your information :)
I will test the new release soon :100:
