### ISSUE TITLE
Add Build insurance `Workflows`

### ISSUE THREAD

**Issue by taha-ghadirian** [bitfoundation/bitplatform#3433]
Due to issue #3419, I noticed that building template could lead to problem on different Os's because of some small changes, 
So I decided to write workflows to insure that templates are really multi platform and can run on every single Dotnet supported Os without error. 

I'm currently working on this issue, please assign it to me, thanks.

**Comment by ysmoradi** [comment]
I'm working on CI/CD
https://github.com/ysmoradi/TodoTemplateDevOps/actions
This is for project templates so we can use it for bitplatform repo CI/CD + developer can use the same GitHub actions in projects that get created with dotnet new bit templates

Note that we've no intention to enable bit.blazorui development on platform other than Windows/Visual Studio

**Comment by taha-ghadirian** [comment]
So let's improve the existing Ci and write per platform Ci's :)

**Comment by msynk** [comment]
@taha-ghadirian & @ysmoradi 
great job guys 👌✌️👍🚀

**Comment by ysmoradi** [comment]
The matrix strategy (#3435) sounds interesting to me
Shall we talk whenever is suitable for you?
https://outlook.office365.com/owa/calendar/YaserMoradiCalendar@BitPlatform.dev/bookings/
