### ISSUE TITLE
Show label in `BitDropDown` in small screens.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3440]
I am using `BitDropDown` by  IsResponsiveModeEnabled=true 
On small screens, I need to show the Label on top of the screen.
Could you please add this future?

![image](https://user-images.githubusercontent.com/23101977/197531273-dbab4421-3f49-4dd2-a662-aa36c1a29d04.png)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
