### ISSUE TITLE
RTL feature for `BitDropDown`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3445]
![image](https://user-images.githubusercontent.com/23101977/197746866-e088aab1-69e5-4295-962a-d92d7024ac0b.png)

I need to be able to use `BitDropDown` in this way.
but RTL is not working fine.
could you please add the RTL feature

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
