### ISSUE TITLE
`Dotnet watch` not working on templates

### ISSUE THREAD

**Issue by taha-ghadirian** [bitfoundation/bitplatform#3484]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Running `Dotnet watch`, it can't detect file changes. 

### Expected Behavior

`Dotnet watch` should automatically track file changes. but it doesn't show anything in terminal

### .NET Version

7.0.100-rc.2.22477.23

**Comment by taha-ghadirian** [comment]
I worked on this problem, but I haven't found reason and solution.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by ysmoradi** [comment]
It was working before
But now it's not working )":
The problem seems to be related to dotnet 7

**Comment by taha-ghadirian** [comment]
> The problem seems to be related to Dotnet 7

Actually, I think it's because Dotnet 7 watch engine can't detect `Condition`s in `.csproj` files, watch command works fine in simple projects, but not in medium and large projects 🤔

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
