### ISSUE TITLE
`BitRadioButtonList` show items horizontally  

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3491]
I need to show `BitRadioButtonList` items in a line

![image](https://user-images.githubusercontent.com/23101977/200164495-e79025aa-29e1-463e-8a49-17061093d90e.png)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by sajadkardel** [comment]
this is closed in #3497 @msynk @msangtarash

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
