### ISSUE TITLE
`BitCheckBox` with image

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3494]
I need to show the image instead of the check box to show checked items.

![image](https://user-images.githubusercontent.com/23101977/200167745-500fb03e-7c4e-4644-ab93-0349a4a59b9b.png)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
