### ISSUE TITLE
Implement `BitButton` in different sizes 

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3500]
I need to style buttons in different sizes of SM / LG /MD
we already have two different styles by the name of BitButtonStyle, I appreciate it if I could have something like this for Size.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
