### ISSUE TITLE
Implement a new button component with loading

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3501]
I need to show the loading on the button and make it disabled while a task is running.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
