### ISSUE TITLE
‍`BitDateRangePicker` value type issue

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3568]
I want to add `BitDateRangePicker` to the edit form as it is returning a value with the type of BitDateRangePickerValue in this way I need to do a lot to handle exceptions I need `BitDateRangePicker` to return two properties for example fromDate and toDate to be easier to use.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.
