### ISSUE TITLE
[Todo-Template] Loading screen remains after complete loading

### ISSUE THREAD

**Issue by taha-ghadirian** [bitfoundation/bitplatform#3575]
### Describe the bug

I tried to customize Todo-Template, here are the steps that I've done:

1) Delete all pages and components (Except some of them)
![image](https://user-images.githubusercontent.com/36773254/203934667-131d0bf0-cca9-452b-83b1-344ef60271ff.png)
![image](https://user-images.githubusercontent.com/36773254/203934713-1f282fc6-bac5-4d26-9a25-4a04e4be7609.png)

2) Remove Bit.BitBlazorUi from the project and install MudBlazorUi. 

3) Remove all contents on the main page and say hello in ‍‍‍`<h1>` :)))

4) Run project. 
Here is the main page:
![image](https://user-images.githubusercontent.com/36773254/203936267-cb7b740f-5e33-4786-9577-974222093e7c.png)

### Github project link: **Development branch**
https://github.com/taha-ghadirian/MudTemplate/commits/Develop
Projects work on this commit: https://github.com/taha-ghadirian/MudTemplate/commit/34e7fa757862aa5d540f0198fea12729f8aa0c3b
But fails on this commit: https://github.com/taha-ghadirian/MudTemplate/commit/b48f142e12fa7fab9d6b2433138da7ea6f05b7ba

**Comment by taha-ghadirian** [comment]
After some investigations I find out that this problem is because this one single line in `MainLayout.Razor.scss`, 
after deleting `.main` this problem happens. Can you help me fix this issue?

```
.main {
    position: relative;
    width: 100%;
    min-height: 100vh;
    padding-top: rem(48px);
    box-sizing: border-box;
    background-color: $SecondaryColor;
    font-family: "Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif;
}
```

**Comment by taha-ghadirian** [comment]
Fixed: https://github.com/taha-ghadirian/MudTemplate/commit/9618896fbc96cfda3f4e9e251afce44af7803393

**Comment by msynk** [comment]
tnx for contacting us.
that loading component is actually a static element rendered in the _Layout.cshtml file to show a custom UI when the Blazor tries to render the app's UI. since it will be shown whenever there is no actual content on any page, you need to have content that will fill the page when the render is done.
