### ISSUE TITLE
Drop down  with Custome content

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3589]
we need to have a drop-down to be able to customize the content of that like image 
could you please provide me with such a component?
![image](https://user-images.githubusercontent.com/23101977/204486356-decc8498-542c-4f64-a960-de9ca27bdc96.png)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
After some investigation & discussion within our team, we've decided that this requested component has too much customization and is not a proper component to be in a component library like `Bit BlazorUI`.
The only part that can be implemented from this request is the new `Panel` (Popover) component which is already in our future plans.
