### ISSUE TITLE
no placeholder in all inputs

### ISSUE THREAD

**Issue by Donyashirazi** [bitfoundation/bitplatform#3598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

the input boxes do not contain a placeholder so that we could style them individually.

### Describe the solution you'd like

we need to be able to change the font color once we choose an item from the box

for example:
before choosing: THR
after choosing: THR(bold)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
@Donyashirazi 
I don't understand the issue.
for example, the `BitTextField` component has a `Placeholder` parameter as you can see in the following image:
![image](https://user-images.githubusercontent.com/6169846/205629053-1e84eb5d-b5c1-4484-b7a7-c9a867d035f8.png)

**Comment by Donyashirazi** [comment]
thanks for the fast reply

I have an input and a drop down. I plan on changing the font color once something is chosen from the drop down but i could not find a placeholder to do so.

**Comment by Donyashirazi** [comment]
yes it is.

`                <TeckDropDown ItemsProvider="LoadOriginDropdownItems"
                              Virtualize=true
                              ShowSearchBox=true
                              CaretDownClass="icon-gps"
                              Placeholder="@FlightLocalizer[nameof(FlightStrings.Origin)]"
                              IsRequired=true
                              Label="@FlightLocalizer[nameof(FlightStrings.SelecteOriginDropDownLabel)]"
                              SearchBoxPlaceholder="@FlightLocalizer[nameof(FlightStrings.Search)]"
                @bind-Value=AvailableRequest.OriginIataCode />`

**Comment by msynk** [comment]
hmm, what is this `TeckDropDown` ? this is not a BitBlazorUI component.

**Comment by Donyashirazi** [comment]
` <BitDropDown ItemsProvider="ItemsProvider"
                     Virtualize="@Virtualize"
                     Placeholder=@Placeholder
                     IsResponsiveModeEnabled=true
                     Label=@Label
                     ShowSearchBox="@ShowSearchBox"
                     SearchBoxPlaceholder=@SearchBoxPlaceholder
                     Value=@Value
                     Items=@Items
                     AutoFocusSearchBox=true
                     ValueExpression="ValueExpression"
                     AriaLabel=@AriaLabel
                     ValueChanged="@((string e) =>OnValueChange(e))">
            <CaretDownFragment>
                <i class="@CaretDownClass" />
            </CaretDownFragment>
        </BitDropDown>`


once a dropdown is chosen can we change the default style?

**Comment by msynk** [comment]
hmm, still I don't understand the problem.
do you want to be notified when an item is selected in the BitDropDown and then change something in an input?
if yes, you can use either the `OnSelectItem` or `SelectedItemChanged` parameters.

**Comment by Donyashirazi** [comment]
Thanks for the comment and sorry for the late reply
I have chosen a gray color for the default font and I want to change it to bold and black once something has been chosen from the dropdown. where can I apply this change to?

**Comment by Donyashirazi** [comment]
I understand, Thank You.

**Comment by msynk** [comment]
@Donyashirazi 
please let me know if the feature I've mentioned solves your problem, so we can close this issue.

**Comment by msynk** [comment]
I'm closing this issue since there was no new activity for it in a long time.
