### ISSUE TITLE
Override styles in isolated format issue.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3918]
I need to override some of the styles of 'BitActionButton' but no need to override the disabled style.
by overriding the main class of `BitActionButton` I am forced to override all related styles like hover and disabled and... 
![Untitled](https://user-images.githubusercontent.com/23101977/218110992-5773be6c-72bb-4bcf-9313-36218d1d5aac.png)

**Comment by msynk** [comment]
since overriding component css classes are not supported, I'm closing this issue.
