### ISSUE TITLE
Some style issues in the multiple different types of buttons

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3919]
The style of buttons has different values.
for example for `BitActionButton` height is set but for `BitLoadingButton` minHeight is set.
and also the height of these two is different.
It is better to set a line height for the text and a default padding or min-height for all buttons and read the values from the theme.
And also it could be valid for other common properties in buttons.
![image](https://user-images.githubusercontent.com/23101977/218124318-01b697e5-e37e-4b44-b6b5-4c20e9592199.png)

**Comment by msynk** [comment]
this issue is resolved
