### ISSUE TITLE
Some issues in style of the input type components

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#3924]
The stretcher of styling in `BitDropDown` is different from others so only by changing the height value we can't achieve the required height.
Color of icons are different
Paddings and gaps between icons and text are set differently.
Font size and font weight in the field are different.
By focusing on elements style of numeric is different from others.
background of the drop-down is not like others.
![Untitled2](https://user-images.githubusercontent.com/23101977/218136980-db096fef-a6aa-4f08-9bec-09103c284771.png)

**Comment by msynk** [comment]
since these problems are resolved, I'm closing this issue.
