### ISSUE TITLE
dotnet new bit-todo doesn't work on Mac M1 computer

### ISSUE THREAD

**Issue by smtm2033** [bitfoundation/bitplatform#4089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

it throws exception because of the compatibility issue of LibSaasbuilder-tool on M1. Are there alternative or turnaround solution? 

### Expected Behavior

can create the project properly

### Steps To Reproduce

dotnet new bit-todo on Mac OS M1 computer

### Exceptions (if any)

Running command 'lsb src/Client/Shared'...
Sass compile directory: src/Client/Shared
Unhandled exception. LibSassHost.SassCompilerLoadException: During loading of Sass compiler error has occurred. Most likely it happened, because the 'libsass.dylib' assembly or one of its dependencies was not found. There is no LibSassHost.Native.osx-* package for the arm64 processor architecture. You can build the 'libsass.dylib' assembly for the current processor architecture by using following instructions - https://github.com/Taritsyn/LibSassHost#os-x-1. ---> System.DllNotFoundException: Unable to load shared library 'libsass' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libsass.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libsass.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libsass.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.2/libsass.dylib' (no such file)

### .NET Version

7.0.102

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by ysmoradi** [comment]
It seems to be related to https://github.com/johan-v-r/LibSassBuilder/issues/48 @msynk

**Comment by msynk** [comment]
@ysmoradi
can't we do something about it in the short term? or should we wait for them to fix it?

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
