### ISSUE TITLE
Fix some small issues of `TodoTemplate` UI

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#4095]
In some screen sizes the sidebar size and sort dropdown position is not correct.

**Comment by msynk** [comment]
could you please submit some pics of the issues?

**Comment by mhrastegari** [comment]
![image](https://user-images.githubusercontent.com/42671084/226130341-b63cf441-35d3-4388-8136-46f2f8aa06e7.png)

**Comment by mhrastegari** [comment]
![image](https://user-images.githubusercontent.com/42671084/226130394-6cd76a56-03b5-4b51-a989-b1699de51210.png)
