### ISSUE TITLE
Add AM/PM format to date range picker

### ISSUE THREAD

**Issue by ajafarip** [bitfoundation/bitplatform#4211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I used bit Daterangepicker and the date range picker only supports 24-hour format.

### Describe the solution you'd like

I think adding this feature would improve the usability of the date range picker for a wider range of users. Additionally, this feature is commonly used in other date/time pickers, so it would help to make the Bit Component date range picker more consistent with other interfaces.

Thank you for considering my suggestion.

Best regards,
Ahmad.

**Comment by msynk** [comment]
hanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
