### ISSUE TITLE
Show a preview before uploading file in `BitFileUpload`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#4305]
I need to show a preview of my image file before uploading it.

**Comment by msynk** [comment]
we can't add this feature to a general-purpose component like BitFileUpload. but you can easily achieve this as explained below:

- get the `FileId` of the files accessible through the `Files` public property of the component
- using the `InputId` public property, get the input element of the component to have access to the files in JS
- now you can read the file in JS and show a preview of it yourself if it's an image type.

**Note**: you can use the `OnChange` event of the component to know when the files are changed in the input element.
