### ISSUE TITLE
`BitOtpInput` getting crazy when its auto filled in iOS

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#4464]
### Summary
When I put Password or suggested text by iOS the OTP input focus gets crazy and even make my keyboard crash!!!

### Screenshots

https://github.com/bitfoundation/bitplatform/assets/42671084/0fb8fb32-6011-452a-a18a-c574b99eb971

**Comment by ysmoradi** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.
