### ISSUE TITLE
Weird behavior of the `FileUpload` in the `TodoTemplate` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitplatform#4518]
Here is the scenario in which I got the problem:
I logged in to the template and then navigated to the edit profile page.
Then, I tried to set an image for my avatar but I got an error!
After that, I tried to upload another image but the error message still was displaying and I couldn't either interact with the uploader using the cancel and pause buttons of the uploader...All of these occurred while the second upload request was still pending.

![freesnippingtool com_capture_20230606214547](https://github.com/bitfoundation/bitplatform/assets/48528003/afba879e-0693-4bc9-8107-1f8d719e1cea)

**Comment by msynk** [comment]
This issue is resolved, so I'm closing it.
