### ISSUE TITLE
`BitDateRangePicker` styles enhancements.

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#4545]
The default background color of `BitDateRangePicker` is white, I expect it to be like other inputs (Others are transparent).
By hovering on the `BitDateRangePicker` style the border and text are not changed like other inputs.
the modal of date is opening in a wrong position 
![image](https://github.com/bitfoundation/bitplatform/assets/23101977/624c659b-89e2-4ed7-9cbd-072c24f435e4)
By focusing on the `BitDateRangePicker` on the right side of the border the color of the default style of the border is shown 
this is the default style of `BitDateRangePicker`(I changed the color to red to be more clear)
![image](https://github.com/bitfoundation/bitplatform/assets/23101977/ebf15265-8c6f-46ce-bc47-09906e060b69)
by focusing on that the style would be like this
![image](https://github.com/bitfoundation/bitplatform/assets/23101977/53704807-e532-4b80-a077-57887b964e28)

**Comment by msynk** [comment]
I'm closing this issue in favor of #4550
