### ISSUE TITLE
Support dark mode for sample code sections

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#4557]
![Screenshot 2023-06-15 at 17 01 06](https://github.com/bitfoundation/bitplatform/assets/42671084/a787ad75-50c7-4ae1-bdae-d644f774f279)

**Comment by msynk** [comment]
this one was fixed a long time ago with the implementation of the new Dark Theme. but the thing is we missed changing the scripts for the MAUI app in the index.html file. It is now fixed in #4558
