### ISSUE TITLE
Miss } in ServerSideAuthTokenProvider.cs file version 5.2.0-pre-03

### ISSUE THREAD

**Issue by hootanht** [bitfoundation/bitplatform#4815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have an issue with ServerSideAuthTokenProvider.cs, I think missed `}` has occurred.
![image](https://github.com/bitfoundation/bitplatform/assets/27281206/195a5950-e3bc-4a47-b5ba-2627199553b4)

**Comment by msynk** [comment]
@hootanht 
which project?

**Comment by hootanht** [comment]
@msynk 

![](https://github.com/bitfoundation/bitplatform/assets/27281206/3b2420bc-2a53-4c92-a641-432af664b18b)

**Comment by msynk** [comment]
@hootanht 
what project? I mean is it coming form `AdminPanel` or `TodoTemplate` or `BlazorDual` ?

**Comment by hootanht** [comment]
TodoTemplate

**Comment by hootanht** [comment]
I Rebuild that, and it seems ok; I create another project it seems to be ok; by the way, it's ok now. Don't be worry, dear Saleh.

**Comment by msynk** [comment]
Thanks, so I'm going to close this issue.
