### ISSUE TITLE
Minor documentation issue / broken link in todo template

### ISSUE THREAD

**Issue by kg** [bitfoundation/bitplatform#4836]
The todo template's readme recommends going to https://bitplatform.dev/todo-template/getting-started for information on how to build it, but that link is a 404.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
