### ISSUE TITLE
Request for more layout examples in the documentation

### ISSUE THREAD

**Issue by Runaho** [bitfoundation/bitplatform#4900]
I am writing to request some enhancements in the documentation site. Specifically, I would appreciate if we could provide some layouts / grids examples that illustrate how to use the nav components in various situations. For example, how to create a closable sidebar, navbar examples, fixed header, a responsive grid, etc. These examples would facilitate the comprehension and implementation for creating own layouts by developers and enable them to adapt their own requirements. Thank you for your attention and hard work.

https://components.bitplatform.dev/overview

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
@Runaho 
did you check our project templates out? I suppose most of what you requested is answered in these templates:

- https://todo.bitplatform.dev (https://bitplatform.dev/todo-template/overview)
- https://adminpanel.bitplatform.dev (https://bitplatform.dev/admin-panel/overview)

**Comment by ysmoradi** [comment]
The Bit.BlazorDual project simply creates the TodoTemplate project for the Web and has nothing to do with BlazorHybrid and BlazorElectron. However, this alone is not the answer to your comment and soon @msynk will also respond.

**Comment by Runaho** [comment]
> The `Bit.BlazorDual` project simply creates the `TodoTemplate` project for the Web and has nothing to do with `BlazorHybrid` and `BlazorElectron`. However, this alone is not the answer to your comment and soon @msynk will also respond.

Yes and you are right about TodoTemplate but does not has sidebar.

**Comment by msynk** [comment]
As @ysmoradi said, the `BlazorDual` project template is a simplified version of our main templates:

https://github.com/bitfoundation/bitplatform/tree/develop/src/Templates/BlazorDual

This project template contains a lot of requirements pre-developed for a real-world application, both in the frontend and backend.

What you suggested about adding new sections on the bit BlazorUI demo website is a good addition and very nice to have, but for now, I'm sorry to say that it's not aligned with our goals and targets in this phase. we neither have the time to develop such new sections nor the proper need for them at the moment.

although, we might be able to put some gists on github for these purposes later.

**Comment by Runaho** [comment]
I'm sorry to hear that, maybe I can contribute in the future.
Please don't misunderstand that I don't intend for you to overwork, under normal circumstances looking at the documentation should be enough to use a framework or library. Saying "Take our demo project there is everything." This idea restrict new people to make own applications using components from scratch. That's the point I'm trying to make. We are planning to use Bit in our enterprise projects in the future btw.
Have a nice day 👋🏻

**Comment by ysmoradi** [comment]
Thanks for your feedback.

Have you reviewed the following docs?
https://bitplatform.dev/admin-panel/development-prerequisites

By acquiring the `Ultimate Package`, not only will you be supported on BitPlatform but also other things that are used in BitPlatform and may cause trouble in your project and create risks or cause delays in your project.

You'll have dedicated support accompanied with online sessions for items such as blazor itself, aspnetcore identity, ef core, the process of publishing on the Store, etc!

In addition, you can request priority for issues that you think may need attention.
https://bitplatform.dev/pricing

**Comment by msynk** [comment]
@Runaho before closing this issue I need to mention we have a plan to add new layout components similar to what Xamarin and MAUI have (like Satck, Grid, ...) in the near future which might help your needs.
Thanks again for contacting us.
