### ISSUE TITLE
 Bit BlazorUI Components are lagging

### ISSUE THREAD

**Issue by ParsaLmn** [bitfoundation/bitplatform#5200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hi
i have deployed admin template blazor server.
all the Bit BlazorUI componnents are lagging which it wasnt lagging on localhost

for example its lagging on fast typing and backspace on input fields in sign in page.

### .NET Version

7

**Comment by msynk** [comment]
it's the nature of the Blazor Server. that's why we put this on our docs:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/4a0818ae-9bc6-4ef1-88a7-b436e6dbae97)

**Comment by ysmoradi** [comment]
Hi @ParsaLmn,

I noticed you haven't explored Blazor WebAssembly, similar to what's showcased at https://adminpanel.bitplatform.dev/. In Blazor Server, logic execution occurs server-side, with the client merely transmitting user interactions and receiving UI updates via websocket. Even a minor task like toggling a checkbox can be impacted. If there's any significant network latency on the user's end, it can lead to the issues you highlighted.

This is why we advocate for Blazor WebAssembly. We're proud to offer the most lightweight libraries available for both Blazor WebAssembly and Blazor Hybrid apps. We believe it's a better choice for many users.

I'd love to hear your thoughts!
