### ISSUE TITLE
BitBlazorUI Android app crashed while working with `BitColorPicker`

### ISSUE THREAD

**Issue by mirshekarm** [bitfoundation/bitplatform#5204]
Hi, While working with the Android app, I noticed that sometimes the app crashes!  For example, when quickly changing the color of the color picker and using some other components.

**Comment by ysmoradi** [comment]
Thanks! Could you please describe other crash scenarios too?

**Comment by mirshekarm** [comment]
> 

I don't remember the rest. Some time ago, I was testing some components when the app crashed. Now, when I tested again, the app had a problem with the color picker.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
this issue is not valid anymore
