### ISSUE TITLE
SignUpRequestDto could not be resolved

### ISSUE THREAD

**Issue by iPazooki** [bitfoundation/bitplatform#5222]
I am receiving a warning in Visual Studio after a successful build. The warning message says `Warning CS1574 XML comment has cref attribute 'SignUpRequestDto' that could not be resolved`. 

This warning is triggered because this path in the documentation: [`Check out <see cref="SignUpRequestDto"/> for an example`](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Shared/AppDataAnnotationsValidator.cs) cannot be found. 
I am wondering whether it is referring to [this file](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Dtos/Identity/SignUpRequestDto.cs). If that is the case, we can resolve the issue by adding `using TodoTemplate.Shared.Dtos.Identity;` to the code.

**Comment by ysmoradi** [comment]
PR is welcome (":
