### ISSUE TITLE
Possible null exception

### ISSUE THREAD

**Issue by iPazooki** [bitfoundation/bitplatform#5224]
The value of [restError](https://github.com/bitfoundation/bitplatform/blob/af98af8c20d47d73d49109d848be365f6fa76eef/src/Websites/Careers/src/Bit.Websites.Careers.Web/Services/Implementations/AppHttpClientHandler.cs#L28C26-L28C26) may sometimes be `null`, although it is not expected. However, [ReadFromJsonAsync](https://github.com/bitfoundation/bitplatform/blob/af98af8c20d47d73d49109d848be365f6fa76eef/src/Websites/Careers/src/Bit.Websites.Careers.Web/Services/Implementations/AppHttpClientHandler.cs#L28C26-L28C26) could still return `null`. Therefore, we need to ensure that the values of `restError.Key` and `restError.Message` are not null as well.

Although it is unlikely that we will receive `null`, we can fix this issue by either suppressing null with `!` (_fastest, but not safest!_) or double-checking all possible null properties to ensure they are not null (_suggested one although it could be unnecessary!_).

**Comment by ysmoradi** [comment]
When the response has an error status code and the Request-ID response header and the response content type is `application/json`, we can be sure that it was handled by our own middleware and the schema is guaranteed. Therefore, we can safely use the `!` operator in this case.
