### ISSUE TITLE
The problem is not building the project

### ISSUE THREAD

**Issue by aasssaa1382** [bitfoundation/bitplatform#5232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The problem in running the project is not building js and css through Severity Code Description Project File Line Suppression State Error MSB4057 The target "BeforeBuildTasks" and where is the problem

### Expected Behavior

Create the files by itself

### Steps To Reproduce

[TestProj.zip](https://github.com/bitfoundation/bitplatform/files/12505536/TestProj.zip)

### Exceptions (if any)
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "npm install sass@1.65.1 typescript@5.1.6 esbuild@0.19.0 --no-save" exited with code 9009.	TestProj.Client.Core	C:\Product\AliJnab\TestProj\src\Client\Core\TestProj.Client.Core.csproj	85	

Severity Code Description Project File Line Suppression State Error MSB4057 The target "BeforeBuildTasks" does not exist in the project.TestProj.Client.Core

### .NET Version

8.0.1

Version Visaul Stuido 17.8.0

bitPlatform 5.5.0

**Comment by ysmoradi** [comment]
Make sure that you've installed `nodejs` and other prerequisites as describe [here](https://bitplatform.dev/templates/development-prerequisites)
