### ISSUE TITLE
Apply bootstrap theme on bit date picker

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitplatform#5251]
### Discussed in https://github.com/orgs/bitfoundation/discussions/5249

<div type='discussions-op-text'>

<sup>Originally posted by **masoodinfo** September  5, 2023</sup>
I am using Bootstrap and its themes in my Blazor project. I have only used your date picker component, not the rest of the components.
How can I make this component look like the other Bootstrap components? OR at least how can I make the input of the date picker similar to bootstrap components?

Additional information:
The Bit.BlazorUI nuget package's version is 5.5.0</div>

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
you can simply use our class/style parameters to achieve any UI design you want.
I'm closing this issue and if you need any specific feature plz let us know in another issue.
