### ISSUE TITLE
Wrong date format in the ExpireDate of the JWT token

### ISSUE THREAD

**Issue by mirshekarm** [bitfoundation/bitplatform#5256]
In the api, in the input of the token creation method, the ExpireDate argument, according to Visual Studio, should be UTC, but you have passed DateTime.Now.  Why?

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/6ed41ed5-f73f-4384-9e4c-b2e727187aa3)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
