### ISSUE TITLE
component css class

### ISSUE THREAD

**Issue by rh1376** [bitfoundation/bitplatform#5261]
how to remove default css style in any component like BitButton? I want to add just my own css class not having default css class. when i add this <BitButton>Styled Button</BitButton> it has "bit-btn bit-btn-pri" class. but i dont want it.

**Comment by msynk** [comment]
@rh1376 Thanks for contacting us.
to change the appearance of the BitButton component you can use the `Class` and `Style` parameters of the component as shown in the demo page of the component here: https://components.bitplatform.dev/components/button#example2
