### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by iPazooki** [bitfoundation/bitplatform#5290]
In some files like [_BitNavChild.razor.cs](https://github.com/bitfoundation/bitplatform/blob/dc3de39fce8bb63ddd7cd8d682a8d829b33a9f5c/src/BlazorUI/Bit.BlazorUI/Components/Nav/_BitNavChild.razor.cs) or [BitChartClipping.cs](https://github.com/bitfoundation/bitplatform/blob/acc71e6b5bf1f9aa119256463124333a7b43b6c4/src/BlazorUI/Bit.BlazorUI.Extras/Components/Chart/Common/BitChartClipping.cs) etc, we can have some minor improvements like:

- Remove redundant usings
- Add `readonly` to the [_AriaCurrentMap](https://github.com/bitfoundation/bitplatform/blob/dc3de39fce8bb63ddd7cd8d682a8d829b33a9f5c/src/BlazorUI/Bit.BlazorUI/Components/Nav/_BitNavChild.razor.cs#L11C58-L11C74)
- Use `Task` instead of `void` for [HandleOnClick](https://github.com/bitfoundation/bitplatform/blob/dc3de39fce8bb63ddd7cd8d682a8d829b33a9f5c/src/BlazorUI/Bit.BlazorUI/Components/Nav/_BitNavChild.razor.cs#L32C24-L32C37)
- Boolean literals should not be redundant like `Nav.GetIsEnabled(Item) == false` which could be `!Nav.GetIsEnabled(Item)` etc, we have this issue in many places in application files.
- using `var` instead of explicit type name

Are you happy with these changes?

**Comment by msynk** [comment]
Thanks for the suggestions.
all good but the last one. the explicit comparison to false is one of our conventions and is there because of the clarity of the code. you can change it from using `==` to `is`.
