### ISSUE TITLE
The number of total downloads of packages on bitplatform website is not up to date

### ISSUE THREAD

**Issue by zahra-yousefi** [bitfoundation/bitplatform#5345]
as you can see in the following image the number of downloads which is +3.5M at the moment is not up to date:

![image](https://github.com/bitfoundation/bitplatform/assets/15306395/0feb5369-7544-4b48-b7cc-2f96e0ff62b8)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
