### ISSUE TITLE
Redundant ButtonType parameter in Link button sample of the `BitActionButton` demo page

### ISSUE THREAD

**Issue by zahrabayatt** [bitfoundation/bitplatform#5376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Remaining ButtonType samples should be removed from BitActionButton from its demo page

**Comment by msynk** [comment]
@zahrabayatt Thanks for filing this issue. I've updated the title for more clarity.

thanks for the PR too 🚀
