### ISSUE TITLE
`Bit.Tooling.CodeGenerator.Task` is not generating client side context anymore

### ISSUE THREAD

**Issue by tahaltf** [bitfoundation/bitplatform#5460]
hey ! 

i use : 
"@bit/bitframework": "^7.8.0",
    "@bit/jaydata": "^1.5.22",

but from some day ago , when i create new api , context files doesnt update in client/src/app

but i see my api in swagger currectly

clear solution and rebuild dont fix my problem

**Comment by ysmoradi** [comment]
Hi Dear @tahaltf 
I need Visual Studio version (For example 17.8)
Run `dotnet --info` in Api folder and paste its result here
I also need to know version of `Bit.Tooling.SourceGenerator` version and your project target framework (for example net6.0)
