### ISSUE TITLE
Code Highlighting for samples in light mode

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5472]
Currently, in the light mode, we use the dark color theme for the sample code which is not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/297e1b4f-1ba0-4078-a883-0441998b99b5)

**Comment by taha-ghadirian** [comment]
Hi Saleh, I'll be happy to work on this; Please assign this one to me if possible. :)
Also, if there is any other information please provide them. 

Thanks.

**Comment by msynk** [comment]
@taha-ghadirian Thanks👌
after some investigation we decided to use [Prism](https://prismjs.com/) as our code highlighter.
I've already poked around this issue a few times before. for example, we have a custom file named `prism-okaidia-bit.css` forked from the main Okaidia theme of the prism.
the thing is this file has some hardcoded colors which need to be replaced with the CSS variables defined in our theme.
if you have any questions just ask here.
