### ISSUE TITLE
BitProgressIndicator animation has a flicker on safari

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#5570]
See where I'm pointing my mouse at when animation ends

https://github.com/bitfoundation/bitplatform/assets/42671084/eca15fe4-1701-4fa1-a97c-06651067635a

**Comment by ysmoradi** [comment]
> See where I'm pointing my mouse at when animation ends
> 
>  Screen.Recording.2023-10-14.at.21.45.32.mov

It's nice!❤
