### ISSUE TITLE
RTL mode

### ISSUE THREAD

**Issue by RezaAccountant** [bitfoundation/bitplatform#5600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I enable RTL in the language settings, the theme does not fold right

**Comment by msynk** [comment]
@RezaAccountant Thanks for contacting us.
We are not supporting RTL at the Theme level, and we are not planning to do so in the near future. But you can use the `IsRtl` parameter in some of our components. If there is something missing please tell us about them.
And if you can, explain your requirements in more detail, or mention another library that has what you need.

**Comment by RezaAccountant** [comment]
Ok thank you

**Comment by RezaAccountant** [comment]
I want add style for change layout to RTL.
what is the best solution for add style sheet ? Core project or web project?

**Comment by msynk** [comment]
You can start by changing the global styles available in the `app.scss` file of the `Core` project. the main thing to change is the `direction` of the root elements to `rtl`.

But remember, changing the whole layout to RTL is not a simple task. you need to update a lot of other stuff for the app to look clean in a right-to-left direction.

Check this address for more information: https://rtlstyling.com/posts/rtl-styling/
