### ISSUE TITLE
Need prefix options for `ChoiceGroup` for indexing the choice group items

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#5605]
Dear Team,

We need a prefix option for ChoiceGroup items as a number / alphanumeric or an image:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/902cf610-835b-406e-84bd-4e38fba18efb)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
