### ISSUE TITLE
Incorrect call to sync `Any` method in the `CategoryController` of the `AdminPanel` project template

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5627]
Currently, there is a wrong call to the sync `Any` linq method in the following line which should be changed to an async call:

https://github.com/bitfoundation/bitplatform/blob/fcb83f2c6da2a1b42c792497b39f977426e96917/src/Templates/AdminPanel/Bit.AdminPanel/src/Server/Api/Controllers/Categories/CategoryController.cs#L76

the ideal change should be something like this:
![image](https://github.com/bitfoundation/bitplatform/assets/6169846/0a00061d-ff04-4315-b002-393fb68afe8a)

**Comment by ssingh3856** [comment]
Can i take this up?

**Comment by ysmoradi** [comment]
Note that this issues are for first contributes only and for the next contributions consider working on issues with "up for grab" label that need more efforts.
So I'd recommend deleting your comment on other issues (I'll handle it, don't worry 💯)

**Comment by ssingh3856** [comment]
sure, Thanks Yaser 😊. I'll be raising a PR for the same.
