### ISSUE TITLE
Redundant `IsDevelopment` check in the startup of the `TodoTemplate` project template 

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5630]
Currently, there is a redundant develop env check in the `Middleware.cs` file of the startup in the `TodoTemplate`:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/0c5c24bd-bd0f-4434-a952-eba84164988f)

the ideal change should be something like this:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/7c5b1967-11a6-43d3-8b51-ce076d27361c)

the line is in the following link:

https://github.com/bitfoundation/bitplatform/blob/fcb83f2c6da2a1b42c792497b39f977426e96917/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Server/Api/Startup/Middlewares.cs#L19

**Comment by lexi1811** [comment]
Hey, 
I am Lexi and I am new to contributing to open source projects.
I would like to try and work on this issue if thats fine? :)

**Comment by ysmoradi** [comment]
> Hey, I am Lexi and I am new to contributing to open source projects. I would like to try and work on this issue if thats fine? :)

Sure, why not? FULL POWER AHEAD! (":

**Comment by lexi1811** [comment]
Perfect, thanks!
I will try my best :)

**Comment by lexi1811** [comment]
Morning,
I just fixed the code and would like to test it but I don't find any testing tutorial in the README's where they are said to be. Locigally since the IsDevelopment is already checked earlier the code should still work, but I don't know if thats the right way to think. What should I do?

**Comment by msynk** [comment]
Thanks for your efforts. 
This change doesn't require much of a test. you can just try to build the project following this doc: https://github.com/bitfoundation/bitplatform/blob/develop/docs/how-to-build.md
Or just push the PR and our CI will build and run the tests for your changes.
