### ISSUE TITLE
Redundant customizations of the culture in the `CultureInfoManager` class after updating to .NET 8 in the `TodoTemplate` project template

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5638]
After updating to .NET 8 a lot of changes applied to the culture in the `CustomizeCultureInfoForFaCulture` method of the `CultureInfoManager.cs` file is redundant.

the only lines of code that is required now are shown in the following image:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/87b9f3ad-967d-4102-b94a-26fe3e593228)

the rest of the method body should be completely removed.

this method starts at this line:
https://github.com/bitfoundation/bitplatform/blob/fcb83f2c6da2a1b42c792497b39f977426e96917/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Shared/Infra/CultureInfoManager.cs#L54

**Comment by Silverbrain** [comment]
Hey @msynk.
I checked the method and I'd like to work on a fix.
I just have one question. Should the last part of the method, where it checks whether the `Calendar` is `PersianCalendar` be removed as well?

**Comment by msynk** [comment]
@Silverbrain Thanks for contacting us and volunteering to resolve this issue.

Yes, all of the content of the method unless the mentioned 3 lines should be removed. 

Also, the last 2 lines of the class which are only used in this method can be removed too. I mean these two lines:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/8d206954-4a3a-49ae-8d3d-8b980adebae6)
