### ISSUE TITLE
Update the title of the `Basic List without virtualization` section of the `BasicList` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5647]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/b4fa8f3d-9853-4da9-9f27-76899332f382)

This title should be changed to `No virtualization`.

The demo file name is `BitBasicListDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by DevanshKyada27** [comment]
Hey @msynk can you please assign me this issue want to work on it.

**Comment by msynk** [comment]
not relevant anymore!
