### ISSUE TITLE
Update the title of the `Basic List with custom role and class` section of the `BasicList` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5648]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/637b77fe-b4f7-4c64-92ef-e7829bd133b1)

This title should be changed to `Customization`.

The demo file name is `BitBasicListDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by MahdiAbbasi7** [comment]
Hi, is it possible that I send another PR for these issues? Because I sent a PR last days for a different issue.

**Comment by Neha5679** [comment]
can you check my first pr for this issue

**Comment by Neha5679** [comment]
please merge it if it is correct for hactoberfest2023

**Comment by msynk** [comment]
@Neha5679 thanks for your contribution. I've reviewed the PR please apply the request change and then it's good to go.
