### ISSUE TITLE
Update the title of the `Basic List with overscan count` section of the `BasicList` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5649]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/883378dd-5d6a-4b2a-bfa1-f7848653aee7)

This title should be changed to `OverscanCount`.

The demo file name is `BitBasicListDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by DevanshKyada27** [comment]
Hey @msynk can I work on this issue.
Can you please assign me this issue.

**Comment by msynk** [comment]
@DevanshKyada27 Sure go ahead 👍
