### ISSUE TITLE
Update the title of the `Default BitPivot` section of the `Pivot` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5655]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/c6cf59fb-6638-46d1-8119-f5236564367b)

This title should be changed to `Basic`.

The demo file name is `BitPivotDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by DevanshKyada27** [comment]
Hey @msynk can I please work on this issue?
Can you please assign me with this issue.

**Comment by manavb2214** [comment]
Hey @msynk !!! Can you please assign me with this issue.

**Comment by manavb2214** [comment]
Hey @msynk !!! Please review the changes !!!
