### ISSUE TITLE
Update the title of the `Customized Accordion` section of the `Accordion` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5672]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/d6608f64-40c6-4609-b96f-15753d610db1)

This title should be changed to `Customization`.

The demo file name is `BitAccordionDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by MahdiAbbasi7** [comment]
Hi, I send a PR for this title and I changed it to Customization.
