### ISSUE TITLE
Multi selection autocomplete input

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#5677]
Please add **Multi selection autocomplete input** Component.

**Comment by zandiarash** [comment]
> @zandiarash Thanks for contacting us. Could you plz provide a link to a similar component?

Please visit [Blazorise autocomplete with multiple selection](https://blazorise.com/docs/extensions/autocomplete)

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/d55003d8-99a9-42c8-be0b-e936fec7b364)

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by zandiarash** [comment]
Also another example from [masastack](https://docs.masastack.com/blazor/components/autocompletes#dense)

**Comment by msynk** [comment]
We've added the ComboBox feature to our BitDropdown component that resolves this issue.
