### ISSUE TITLE
Incorrect capitalization of the `Checkbox` in the Nav menu of the bit BlazorUI docs

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5678]
Incorrect capitalization of the `Checkbox` in the Nav menu of the bit BlazorUI docs:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/c853d1fc-4460-401a-b04c-54a74756f683)

the title has a capital `B` in it which is not correct. the correct value is `Checkbox`.

the file that contains the nav settings is `NavMenu.razor.cs` in the `Bit.BlazorUI.Demo.Client.Core` project.

the line that needs to be changed is the following:
https://github.com/bitfoundation/bitplatform/blob/4321ff327a51f2238e6114af139eb5965c4be35a/src/BlazorUI/Demo/Client/Core/Shared/NavMenu.razor.cs#L34

**Comment by ssingh3856** [comment]
Can i take this up?
