### ISSUE TITLE
Update the title of the `With Custom Style` section of the `Icon` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5681]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/cee4089b-5305-4615-bed4-65a3332acfb6)

This title should be changed to `CSS Style`.

The demo file name is `BitIconDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by ssingh3856** [comment]
Can i take this up?
