### ISSUE TITLE
Update the title of the `Controlled BitIcon` section of the `Icon` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5682]
The current title of this section is too long and not appropriate:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/6d11fa73-021a-4a53-813b-2aad10b0ba42)

This title should be changed to `Events`.

The demo file name is `BitIconDemo.razor` in the `Bit.BlazorUI.Demo.Client.Core` project.

**Comment by ssingh3856** [comment]
Can i take this up?
