### ISSUE TITLE
Incorrect page title of the `Scrollable` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5683]
Currently, the the title of the `Scrollable` demo page starts with `BitScrollable` which is not correct. The correct value does not have `Bit` at the start and should be `Scrollable`.

The line that needs to be updated is in this link:
https://github.com/bitfoundation/bitplatform/blob/4321ff327a51f2238e6114af139eb5965c4be35a/src/BlazorUI/Demo/Client/Core/Pages/Components/ScrollablePane/BitScrollablePaneDemo.razor#L4

**Comment by ssingh3856** [comment]
Can i take this up?

**Comment by ShayanFaghihi** [comment]
Hello,
I would like to contribute on this issue. 
Thanks

**Comment by msynk** [comment]
@ShayanFaghihi Thanks for informing us, go ahead 👌
