### ISSUE TITLE
Incorrect page title of the `Separator` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5684]
Currently, the the title of the `Separator` demo page starts with `BitSeparator` which is not correct. The correct value does not have `Bit` at the start and should be `Separator`.

The line that needs to be updated is in this link:
https://github.com/bitfoundation/bitplatform/blob/4321ff327a51f2238e6114af139eb5965c4be35a/src/BlazorUI/Demo/Client/Core/Pages/Components/Separator/BitSeparatorDemo.razor#L4

**Comment by ssingh3856** [comment]
Can i take this up?

**Comment by msynk** [comment]
Thanks for your attention, but the issues labeled with `good first issue` are only for the first contributors, and more than one PR for them from a single contributor is not acceptable for our repository.
