### ISSUE TITLE
Incorrect page title of the `Stack` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5685]
Currently, the the title of the `Stack` demo page starts with `BitStack` which is not correct. The correct value does not have `Bit` at the start and should be `Stack`.

The line that needs to be updated is in this link:
https://github.com/bitfoundation/bitplatform/blob/4321ff327a51f2238e6114af139eb5965c4be35a/src/BlazorUI/Demo/Client/Core/Pages/Components/Stack/BitStackDemo.razor#L4

**Comment by ssingh3856** [comment]
Can i take this up ?

**Comment by msynk** [comment]
Sure, go ahead 🚀

**Comment by ssingh3856** [comment]
I already have a PR open for an existing issue, will be looking at the
‘up-for-grabs’ label next but Thanks anyways😊
