### ISSUE TITLE
Incorrect page title of the `Sticky` demo page

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5686]
Currently, the the title of the `Sticky` demo page starts with `BitSticky` which is not correct. The correct value does not have `Bit` at the start and should be `Sticky`.

The line that needs to be updated is in this link:
https://github.com/bitfoundation/bitplatform/blob/4321ff327a51f2238e6114af139eb5965c4be35a/src/BlazorUI/Demo/Client/Core/Pages/Components/Sticky/BitStickyDemo.razor#L4

**Comment by snehpr966** [comment]
Please assign. I am interested to contribute

**Comment by HarshVR1947** [comment]
Made the changes please check and merge
