### ISSUE TITLE
Add required Dotnet workloads to `CodeSpaces` config

### ISSUE THREAD

**Issue by taha-ghadirian** [bitfoundation/bitplatform#5700]
### Is your feature request related to a problem? Please describe the problem.

I'm trying to build BlazorUI project on CodeSpaces, 
But the CodeSpaces config doesn't have required workloads to build BlazorUi solution (Android workloads, wasm workloads, etc...).

And if anyone wants to install workloads with `dotnet workload restore`, it throws permission denied error. 
![image](https://github.com/bitfoundation/bitplatform/assets/36773254/fc951ea2-bed8-4909-af19-936480cd168d)

### Describe the solution you'd like

Pre-install workloads, (Disadvantage: will increase CodeSpace launch time)
or setup CodeSpaces config file permissions, so if anyone wants them, they can easily install.

**Comment by ysmoradi** [comment]
Please be aware that executing `dotnet workload install maui` is not compatible with Linux. Even if you manage to make it function, the question arises: How do you intend to conduct testing for Android, iOS, Windows, and macOS applications within a Linux virtual machine?
