### ISSUE TITLE
improve fonts

### ISSUE THREAD

**Issue by Neha5679** [bitfoundation/bitplatform#5745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I would like to add some new fonts in hero section which will be eye catching

**Comment by msynk** [comment]
@Neha5679 Thanks for contacting us.
Could you please be more specific and explain more about the issue?
We have multiple products and websites and I don't understand the suggestion.

**Comment by Neha5679** [comment]
Sure
![Screenshot (124)](https://github.com/bitfoundation/bitplatform/assets/129548970/99ae3bac-f906-4151-8abe-f9b2dafd8634)
Fonts used in navbar and in hero section is looking dull if we will add some animated word in bit platform it will be good for eye catching.

**Comment by msynk** [comment]
Thanks a lot for sharing your suggestions with us. I suggest starting a discussion and explaining your ideas in it instead of here.
You can create a new discussion here: https://github.com/orgs/bitfoundation/discussions

SO I'm closing this issue.
