### ISSUE TITLE
Update the number of nuget packages downloads on the `Platform` website

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5747]
The number of total downloads of packages on the `About us` page of the `Platform` website should be updated to `3.7M` now:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/dee5452e-92c7-40b8-9bf5-48f5d8cac9a4)

the line that needs to be changed is in the following link:
https://github.com/bitfoundation/bitplatform/blob/27634e0ffb8ea149275016b9dca2533119c59a5d/src/Websites/Platform/src/Bit.Websites.Platform.Web/Pages/AboutUsPage.razor#L49

**Comment by zahra-yousefi** [comment]
@msynk is it ok for me to take care of this issue?

**Comment by msynk** [comment]
@zahra-yousefi sure, go ahead 🚀
