### ISSUE TITLE
Update the number of nuget packages downloads in the root `README.md` file

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitplatform#5748]
The number of total downloads of packages in the README file should be updated to `3.7M` now:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/185767cf-c921-45fb-bbff-98c69b993b81)

the line that needs to be changed is in the following link:
https://github.com/bitfoundation/bitplatform/blob/27634e0ffb8ea149275016b9dca2533119c59a5d/README.md?plain=1#L9

**Comment by bitsali** [comment]
@msynk if it's possible, I want to take care of this issue.

**Comment by msynk** [comment]
@bitsali sure go ahead.
