### ISSUE TITLE
Incorrect naming for the `appSettings` variable 

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#5827]
I noticed the variable name `appsettings` is not correct in some places in code, like this:
![image](https://github.com/bitfoundation/bitplatform/assets/6169846/edfab4a9-9875-413a-8cc5-7a66e8905102)

it is better to rename these to `appSettings`.

**Comment by msynk** [comment]
@zandiarash Thanks for contacting us.
could you please share more information about the issue? where does this naming problem happen?
