### ISSUE TITLE
Unable to Load Image with BitImage Component

### ISSUE THREAD

**Issue by pratiksha-94** [bitfoundation/bitplatform#5895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The image is not loading when using the BitImage component.

### Expected Behavior

![CodeUsing BitImage](https://github.com/bitfoundation/bitplatform/assets/121862908/2eadf126-0359-404e-bb68-59c34a10e474)
![Output](https://github.com/bitfoundation/bitplatform/assets/121862908/cdf65cdf-e62a-4441-87ec-4a5b7d6a6c66)
I have tried JPG PNG and SVG images but image is not loading
I am running my project on web.

### .NET Version

net8.0

**Comment by mhrastegari** [comment]
@pratiksha-94 Thanks for contacting us.
Since you're putting your images in `Core` project you need to specify your image source (or any file to any component or element) like this:

`_content/RioPlay.Client.Core/images/ss.png`

**Comment by pratiksha-94** [comment]
Thank you. Issue got resolved
