### ISSUE TITLE
Update the Twitter Logo to it's latest one (X)

### ISSUE THREAD

**Issue by niranjan-kurhade** [bitfoundation/bitplatform#5911]
As we all that the logo of Twitter has been changed, so we should update it to it's latest one (X)

### Reproduce steps

Go to footer of https://bitplatform.dev/
### Expected result

Logo should be updated with its latest logo.

### Actual result

Still old logo
### Additional detail

![image](https://github.com/bitfoundation/bitplatform/assets/97905637/c5a7a34c-a6f0-4561-af63-dbbd5843faed)

**Comment by niranjan-kurhade** [comment]
Please assign me this issue if it is a valid one.

**Comment by msynk** [comment]
@niranjan-kurhade Thanks for contacting us. it seems ok, go ahead plz.
