### ISSUE TITLE
How to make player page responsive.

### ISSUE THREAD

**Issue by Spiyu** [bitfoundation/bitplatform#5930]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

![Screenshot (94)](https://github.com/bitfoundation/bitplatform/assets/143399918/a6ab7c02-4e85-4dc6-a604-788c7883df31)
![Screenshot (93)](https://github.com/bitfoundation/bitplatform/assets/143399918/61232667-9b03-4c53-9661-0f833113bdaa)

### Describe the solution you'd like

I want this played video and their related video and content shown in one responsive page .

**Comment by msynk** [comment]
@Spiyu Thanks for contacting us.

Based on your explanations, it seems this problem is not related to the bit BlazorUI directly. If you still think this is an issue of our product, please explain it in more detail.

**Comment by Spiyu** [comment]
ok
