### ISSUE TITLE
[DOC] Add license information in README

### ISSUE THREAD

**Issue by adityadeshpande09** [bitfoundation/bitplatform#5953]
Add the license information in README file.

### Expected result
License information would be present in README

### Actual result
No License information

**Comment by msynk** [comment]
@adityadeshpande09 Thanks for contacting us.
This is a good suggestion and it would be appreciated if you could submit a PR for it too.

**Comment by ysmoradi** [comment]
![image](https://github.com/bitfoundation/bitplatform/assets/5352980/f17f2413-d5dc-4bef-80c5-45cbcbd5a4a1)
@msynk ?

**Comment by msynk** [comment]
@ysmoradi it's a good practice to have a link to the license file in the readme.
btw, what is this UI? mine is like this 😁
![image](https://github.com/bitfoundation/bitplatform/assets/6169846/90f45546-a8fe-4eb9-abd6-5f9a498b95b7)

**Comment by ysmoradi** [comment]
Those UI changes will be available to you soon as well and I think with such a UI change, that convection will gone!

**Comment by msynk** [comment]
@ysmoradi Oh in that case you are right then, so we can close this issue.
