### ISSUE TITLE
Change timepicker UI in `BitDateRagnePicker` to match `BitTimePicker` for better UX and responsivene

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#5987]
As a user, I want to have a consistent and user-friendly experience when selecting a date and time using Bit components. Currently, the timepicker UI in `BitDateRagnePicker` is different from the `BitTimePicker` component, which can cause confusion and inconsistency. Moreover, the current timepicker UI is not very responsive for mobile devices, as it requires the user to type the hour and minute manually.

**Comment by Wayne-Mather** [comment]
@Cyrus-Sushiant I just tested this on my S21+ and also browser iPhone SE mode and the time picker was working as expected both on the "emulated" and real device. The DateRangePicker demo with TimePicker became more responsive by allowing the user to switch between calendar mode and time mode.

The text is unable to be read entirely as there is insufficient width to display all the text but that would have to be expected.

Can you confirm your issues still exist on the last release?

**Comment by Cyrus-Sushiant** [comment]
> @Cyrus-Sushiant I just tested this on my S21+ and also browser iPhone SE mode and the time picker was working as expected both on the "emulated" and real device. The DateRangePicker demo with TimePicker became more responsive by allowing the user to switch between calendar mode and time mode.
> 
> The text is unable to be read entirely as there is insufficient width to display all the text but that would have to be expected.
> 
> Can you confirm your issues still exist on the last release?

This issue has been fixed in the latest version, but If you’re still experiencing issues with the latest release, please provide more details about the problems, such as any screenshot, specific scenarios where the picker is not functioning as expected, and the version number of the release you’re testing. This information will help in confirming whether the issues persist or in finding a suitable solution.

**Comment by msynk** [comment]
fixed!
