### ISSUE TITLE
I have an error when I'm running my bit platform app

### ISSUE THREAD

**Issue by AbbasKashi69** [bitfoundation/bitplatform#6023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when I wanna run my application on webassembly I have an error 
my project has 4+ layer more 
Gym.AppServices
Gym.DB
Gym.DeviceService
Gym.Messaging

I attach photo of error
I hope someone help me
![Screenshot 2023-11-14 102140](https://github.com/bitfoundation/bitplatform/assets/77057998/7929f82f-fdfb-4230-a435-7cc201a6a6cc)

### Exceptions (if any)

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'ApplicationParts' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)	Gym.Client.Web	E:\Project_WEB\GymRollCall2\Gym2\Gym\src\Client\Web\obj\Debug\net7.0\Gym.Client.Web.MvcApplicationPartsAssemblyInfo.cs	14	Active

**Comment by ysmoradi** [comment]
Hi Dear @AbbasKashi69 
Please provide more information (as much as possible)
Which version of Visual Studio and dotnet?
Which project template? which version?

**Comment by AbbasKashi69** [comment]
sure
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.4
dot net 7.0
bit platform admin ui 4.9.9

**Comment by AbbasKashi69** [comment]
actually I can send to you my project and you test it.
are you ok??

**Comment by ysmoradi** [comment]
Yes, that's fine, you could send it to my telegram account in 7zip format
Close the VS and run Clean.bat in order to reduce the file size
