### ISSUE TITLE
How to navigate to native xaml page?

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#6024]
Hello dear develop team.
Do you have any plan to implement **Barcode And QRCode Scanner** component?
Or is there a way to navigate to another ``XAML`` file through the **``Client.Core`` Home Page** with sending and receiving data?

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/50ca000d-128d-4c6d-8345-5e7b43fa4df0)

**Comment by msynk** [comment]
@zandiarash Thanks for contacting us.
Unfortunately, we don't have any plan for the near future to implement these special components into the bit BlazorUI library.

**Comment by ysmoradi** [comment]
Register `IPubSubService` by calling `services.AddSingle` in Blazor Hybrid, Electron and WebAssembly and use `services.AddScoped` for Blazor Server.
Then inject `IPubSubService` into `MainPage.xaml.cs`'s constructor and subscribe to your messages that you're going to publish in razor pages.
While your message that gets published from razor page arrives in `MainPage.xaml.cs`, you can open any xaml page you want.
Let me know if you need more guidance.
@zandiarash

**Comment by zandiarash** [comment]
Thanks for guidance but I have a problem
This is where I ``AddScoped`` **IPubSubService** 

![A1](https://github.com/bitfoundation/bitplatform/assets/10775073/37e9941a-d4ea-4707-b03d-da5a9ebdf67f)

This is my ``MainPage.xaml.cs``
![A2](https://github.com/bitfoundation/bitplatform/assets/10775073/61f59561-a77f-4bf9-afa1-4e957d7b515f)

And This is my ``HomePage`` of **Core** project
![A3](https://github.com/bitfoundation/bitplatform/assets/10775073/38b06e1d-5668-44ca-bcb0-920f4aa7769f)

But this line of code never will be traced.
![image](https://github.com/bitfoundation/bitplatform/assets/10775073/f4fe3f73-a780-422a-aafb-8089dd872048)

My message ``Go_Scan`` is not listed even after running this line of code.
Is my mistake here ?
![image](https://github.com/bitfoundation/bitplatform/assets/10775073/a5e71fdc-db95-4c77-be7b-bab6027691c0)


I will appreciate you if you could tell my mistake.
Thanks @ysmoradi

**Comment by ysmoradi** [comment]
Take a look at the first photo you've provided, you've forgotten to remove existing `IPubSubService` registration and you're registering that service again which has no side effect for Microsoft.Ext.DI

**Comment by zandiarash** [comment]
> Take a look at the first photo you've provided, you've forgotten to remove existing `IPubSubService` registration and you're registering that service again which has no side effect for Microsoft.Ext.DI

Sorry, I'm a little confused.
What do you mean by existing ``IPubSubService`` ?
In the first picture, line ``42-46`` is written by me which were not exist before.
Obviously Line ``43`` will not be executed since ``#if BlazorServer`` doesn't let it to run. Thus  **only** line ``45`` will be excecuted.
By the way there is ``services.AddClientSharedServices();`` here which has already addScoped ``IPubSubService``.
Does It mean that I should not AddScope ``IPubSubService`` again ?
Although <ins>with or without</ins> ``AddScope IPubSubService``  in **MauiProgram.cs** nothing works for me.
![image](https://github.com/bitfoundation/bitplatform/assets/10775073/9a41ab9e-c9d7-4c82-8525-746a54ce5a1e)

**Comment by zandiarash** [comment]
Finally I've found the solution.
Seems the sequence of registering services matters.

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/188bcfe0-0d53-40b6-b3ac-15fcf81dfc86)


I've moved this line 
` services.AddScoped<IPubSubService, PubSubService>();`
After 
`services.AddClientSharedServices();`
Now everything works as expected

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/059d69ba-0769-4cf3-b178-31e489c1ea6a)

By the way thanks to you dear @ysmoradi You helped me alot.
