### ISSUE TITLE
Change type of value parameter to generic type in `BitTimePicker`

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#6060]
This is a feature request for the `BitTimePicker` component. Currently, the type of the parameter value is fixed to TimeSpan, which limits the use cases of the component. For example, to use BitTimePicker to select a DateTime or a TimeOnly value, they have to be converted to and from TimeSpan, which is not convenient and may cause errors.

The proposed feature is to change the type of the parameter value to a generic type, such as T, and provide a converter function that can convert T to and from DateTime. This way, the `BitTimePicker` component can be used with any type of time value, such as TimeSpan, TimeOnly, DateTime, or even custom types. The converter function can be specified as a parameter of the component, or as a service that can be injected.

This feature would make the BitTimePicker component more flexible and versatile, and allow users to use it for different scenarios.

**Comment by msynk** [comment]
not relevant anymore!
