### ISSUE TITLE
Supporting Checkbox for ChoiceGroup

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#6082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am using  BitUI Component ChoiceGroup for showing options which are shown as single selection using RadioButtons

In some cases I would like to use Checkbox for multiple selection, supporting Checkbox inside ChoiceGroup would be great

### Describe the solution you'd like

ChoiceGroup to support Checkbox for multiple selection of items

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
not relevant anymore
