### ISSUE TITLE
support for keyboard shortcuts for BitButton

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#6112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can we map Keyboard button for BitButton for example Enter for submission also Left or Right Arrow keys for navigation etc.

### Describe the solution you'd like

support Keyboard Keys for BitButton

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
check out #6123 
using the `Butil` tool you can now easily register keyboard shortcuts in your Blazor apps.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
