### ISSUE TITLE
Show code in https://components.bitplatform.dev/ site shows Oops, something went wrong...

### ISSUE THREAD

**Issue by OmidAtaei1984** [bitfoundation/bitplatform#6224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hi. when you click on "Show code" in usage section of samples, it shows "Oops, something went wrong..."
![2023-12-04](https://github.com/bitfoundation/bitplatform/assets/141127716/22519626-5ee4-4675-80b5-c4ca17a3d8db)

**Comment by msynk** [comment]
@OmidAtaei1984 Thanks for the issue. we are working on it.
