### ISSUE TITLE
Boilerplate on MacOS fails to log in user due to a crypto exception CSSMERR_DL_DATASTORE_DOESNOT_EXIST

### ISSUE THREAD

**Issue by garunski** [bitfoundation/bitplatform#6262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Creating a new project with Boilerplate template fails on signing a user in with a crypto exception.

### Expected Behavior

Should be able to login.

### Steps To Reproduce

create a new project with the template 

### Exceptions (if any)

```
Interop+AppleCrypto+AppleCFErrorCryptographicException: The operation couldn’t be completed. (OSStatus error -25294 - CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST)
         at Interop.AppleCrypto.NativeCreateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 dataHash, PAL_HashAlgorithm hashAlgorithm, PAL_SignatureAlgorithm signatureAlgorithm)
         at Interop.AppleCrypto.CreateSignature(SafeSecKeyRefHandle privateKey, ReadOnlySpan`1 dataHash, PAL_HashAlgorithm hashAlgorithm, PAL_SignatureAlgorithm signatureAlgorithm)
         at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
```

### .NET Version

8.0.100

### Anything else?

Essentially the issue is with the encryption of the bearer token. 

https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/Boilerplate/Bit.Boilerplate/src/Boilerplate.Server/Extensions/IServiceCollectionExtensions.cs#L81

I fixed the problem by removing the `using` statement around the certificate. 

```
var signingCert = new X509Certificate2(certificatePath,
    appSettings.IdentitySettings.IdentityCertificatePassword,
    OperatingSystem.IsWindows()
        ? X509KeyStorageFlags.EphemeralKeySet
        : X509KeyStorageFlags.DefaultKeySet);
var rsaPrivateKey = signingCert.GetRSAPrivateKey();
```

alternatively, using the constructor for `X509SecurityKey` also works:

```
var signingCert = new X509Certificate2(certificatePath,
  appSettings.IdentitySettings.IdentityCertificatePassword,
  OperatingSystem.IsWindows() ? X509KeyStorageFlags.EphemeralKeySet : X509KeyStorageFlags.DefaultKeySet);
var securityKey = new X509SecurityKey(signingCert);
```

I think something gets lost in the key storage pointers once the certificate is destructed.

**Comment by ysmoradi** [comment]
I'm also open to this change:

```csharp
using X509Certificate2 signingCert = new X509Certificate2(certificatePath, appSettings.IdentitySettings.IdentityCertificatePassword, OperatingSystem.IsWindows() ? X509KeyStorageFlags.EphemeralKeySet : X509KeyStorageFlags.DefaultKeySet);
var validationParameters = new TokenValidationParameters
{
      ClockSkew = TimeSpan.Zero,
      RequireSignedTokens = true,
      ValidateIssuerSigningKey = true,
      IssuerSigningKey = new X509SecurityKey(signingCert),
```

![image](https://github.com/bitfoundation/bitplatform/assets/5352980/ae95b941-c13f-4ef4-b33b-c28b568fcddc)

**Comment by garunski** [comment]
> Could you please check this code too?
> 
> ```cs
> using X509Certificate2 signingCert = new X509Certificate2(certificatePath, appSettings.IdentitySettings.IdentityCertificatePassword, OperatingSystem.IsWindows() ? X509KeyStorageFlags.EphemeralKeySet : X509KeyStorageFlags.DefaultKeySet);
> RSA rsaPrivateKey = signingCert.GetRSAPrivateKey()!;
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/5352980/289190719-cb56e9e3-da0f-4f9e-9329-3824fa8f8b87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNzYwOTcsIm5iZiI6MTcwMjA3NTc5NywicGF0aCI6Ii81MzUyOTgwLzI4OTE5MDcxOS1jYjU2ZTllMy1kYTBmLTRmOWUtOTMyOS0zODI0ZmE4ZjhiODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMjI0OTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGMyMWVkODI3ODZhY2QwYWIxOTgxNGM2MDUwOWEwM2ZjMmE4ZjA3OTI0YWIwY2I0ZTlmZGQ3NjUyYjAwNmRkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.emnpl7XlZuD6jJyRtsjCcQPwpz20aBSyWdKwphzg1Ec)
> 
> With this new change, I'm basically keeping certificate alive until `SecurityKey` gets created.

Same error.

**Comment by garunski** [comment]
> I'm also open to this change which is based on your hint. (The `using` block exists though)
> 
> ```cs
> using X509Certificate2 signingCert = new X509Certificate2(certificatePath, appSettings.IdentitySettings.IdentityCertificatePassword, OperatingSystem.IsWindows() ? X509KeyStorageFlags.EphemeralKeySet : X509KeyStorageFlags.DefaultKeySet);
> var validationParameters = new TokenValidationParameters
> {
>       ClockSkew = TimeSpan.Zero,
>       RequireSignedTokens = true,
>       ValidateIssuerSigningKey = true,
>       IssuerSigningKey = new X509SecurityKey(signingCert),
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/5352980/289190912-ae95b941-c13f-4ef4-b33b-c28b568fcddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNzYwOTcsIm5iZiI6MTcwMjA3NTc5NywicGF0aCI6Ii81MzUyOTgwLzI4OTE5MDkxMi1hZTk1Yjk0MS1jMTNmLTRlZjQtYjMzYi1jMjhiNTY4ZmNkZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMjI0OTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzlhOGFjMWZjZTlkNmIzYTU1YWY5YTk4OGJlNmQzZDQ1ZTlkZDBlYzA2YjMyNzhkOGMzOGZkZTRmMmViYTg2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H5oqE6jzSToqxwrx5a8xcOk6RrTJRZZFT6M0o_LRa-8)

New Error,  same vein tho.

```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Security.Cryptography.CryptographicException: m_safeCertContext is an invalid handle.
         at System.Security.Cryptography.X509Certificates.X509Certificate.ThrowIfInvalid()
         at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PublicKey()
         at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
         at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PublicKey()
         at Microsoft.IdentityModel.Tokens.SupportedAlgorithms.IsSupportedAlgorithm(String algorithm, SecurityKey key)
```

**Comment by ysmoradi** [comment]
Ok, could you please send a PR with the following code?
I can also handle this.

```csharp
X509Certificate2 signingCert = new X509Certificate2(certificatePath, appSettings.IdentitySettings.IdentityCertificatePassword, OperatingSystem.IsWindows() ? X509KeyStorageFlags.EphemeralKeySet : X509KeyStorageFlags.DefaultKeySet);
var validationParameters = new TokenValidationParameters
{
      ClockSkew = TimeSpan.Zero,
      RequireSignedTokens = true,
      ValidateIssuerSigningKey = true,
      IssuerSigningKey = new X509SecurityKey(signingCert),
```
