### ISSUE TITLE
Maui ApplicationId property in the csproj should reflect the template name

### ISSUE THREAD

**Issue by garunski** [bitfoundation/bitplatform#6294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Maui ApplicationId property in the csproj should reflect the template name.

https://github.com/bitfoundation/bitplatform/blob/14cb665bb3e2b557b7ea223723a8c5c2046fd360/src/Templates/Boilerplate/Bit.Boilerplate/src/Client/Boilerplate.Client.Maui/Boilerplate.Client.Maui.csproj#L18

The current setting has it as `<ApplicationId>com.bitplatform.BP.Template</ApplicationId>` which is not getting replaced.

### Expected Behavior

the name is something that is based on the template name: <ApplicationId>com.Boilerplate</ApplicationId>

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by ysmoradi** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by ysmoradi** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
