### ISSUE TITLE
Back button issue in bit project template

### ISSUE THREAD

**Issue by afshinalizadeh** [bitfoundation/bitplatform#6558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, could you please check these two samples? 
One of them is a pure Blazor project and the other is a Bit project template. 
I want to close a component using the Back button. 
I display the component and add the current page to **history.pushState**. I detect when the user presses the Back button using the **popstate** event, so I can close the component. This approach works in the pure Blazor project, but it does not work in the Bit project template. 

### Steps To Reproduce

1: Go to the **Counter** menu.
2: Press "Click me".
3: Press Back button
In the bit project the counter back to zero. But in the pure project it's ok. 
[BlazorAppHandleBackButton.zip](https://github.com/bitfoundation/bitplatform/files/13907171/BlazorAppHandleBackButton.zip)
[BitHandleBackButton.zip](https://github.com/bitfoundation/bitplatform/files/13907249/BitHandleBackButton.zip)

**Comment by msynk** [comment]
@afshinalizadeh Thanks for contacting us.
we are investigating this issue.

**Comment by msynk** [comment]
It seems the root cause of the issue is coming from the `Navigating` parameter of the Blazor `Router` component. somehow setting this parameter causes a page refresh even when the url has not changed.
