### ISSUE TITLE
Add Mapbox component

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitplatform#6633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There is a solution for displaying maps in JavaScript called [Mapbox](https://docs.mapbox.com/mapbox-gl-js/guides/), for which you can write a Blazor wrapper.

### Describe the solution you'd like

Write a Blazor component for Mapbox.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
after some investigation, we decided not to work on this issue. it's a huge investment for us to add such a thing to our tooling and we don't have that many resources for now.
