### ISSUE TITLE
`UserSecretsId` is not unqiue for each generated project

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitplatform#6634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we create a project based on Bitplatform templates, the UserSecretsId in Server project is duplicated.

### Expected Behavior

In this scenario must generate a new UserSecretsId for every new project.

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.
btw, a PR from you is welcome for this.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
