### ISSUE TITLE
Adding prefix and suffix functionality for `BitNumericTextField`

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#6657]
We need to show the unit of the item in `BitNumericTextField`exactly what we have in `BitTextField` https://components.bitplatform.dev/components/textfield#example6
Also `BitNumericTextField` already has the suffix but it is not as like as the suffix in `BitTextField`

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
