### ISSUE TITLE
CultureInfoHelper : File not found error

### ISSUE THREAD

**Issue by hrshfa** [bitfoundation/bitplatform#6670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in page https://components.bitplatform.dev/components/daterangepicker link to CultureInfoHelper .cs github link is incorrect.
incorrect link is:https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Demo/Client/Core/Helpers/CultureInfoHelper.cs

correct link is:
https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Demo/Client/Bit.BlazorUI.Demo.Client.Core/Helpers/CultureInfoHelper.cs

![image](https://github.com/bitfoundation/bitplatform/assets/88160323/c0266656-a5ad-49f3-984f-ac3030ba895b)

### Expected Behavior

open link with this url:
https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Demo/Client/Bit.BlazorUI.Demo.Client.Core/Helpers/CultureInfoHelper.cs

### .NET Version

any

**Comment by ysmoradi** [comment]
Greeting
It seems [it's pointing](https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Demo/Client/Bit.BlazorUI.Demo.Client.Core/Pages/Components/Inputs/DateRangePicker/BitDateRangePickerDemo.razor#L133) to the correct location.
I also checked https://components.bitplatform.dev with [Broken Link Checker](https://www.deadlinkchecker.com/website-dead-link-checker.asp)
It seems for some reason, your pwa app is out dated /-:

**Comment by hrshfa** [comment]
It seems it is fixed, thanks
