### ISSUE TITLE
Custom CSS Not Applied to BitTextField in Home.razor

### ISSUE THREAD

**Issue by mostafa1374** [bitfoundation/bitplatform#6758]
I added a `BitTextField` tag in `Home.razor` and included the corresponding CSS in `Home.razor.css`. I defined a CSS class called `custom-field`, but the `BitTextField ` does not reflect the defined style.
### Reproduce steps

1. Navigate to the [home.razor](https://github.com/mostafa1374/bit-blazorui-playground/blob/develop/Components/Pages/Home.razor#L19) file.
2. Check the [home.razor.css](https://github.com/mostafa1374/bit-blazorui-playground/blob/9619a9df2c6fc4cb8814a363842c55af62f1e509/Components/Pages/Home.razor.css#L41) file for the corresponding CSS.

### Expected result
I expect the custom CSS to be applied to the `BitTextField` element.

### Actual result
The custom CSS is not being applied to the `BitTextField` element.

### Additional detail
If I use an inline style tag in the `home.razor` page, it works as expected, and the custom class is applied.

**Comment by msynk** [comment]
@mostafa1374 Thanks for contacting us.
since you are using the isolated CSS in Blazor, did you use the `::deep` selector before your CSS classes?

**Comment by msynk** [comment]
as far as I can see, all the CSS classes are applied:

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/0f7842f2-deb9-462f-96e2-8e6b6b23a7c1)

![image](https://github.com/bitfoundation/bitplatform/assets/6169846/3ec69b08-bb6c-4f4e-a237-d0f97262b9b6)

**Comment by msynk** [comment]
I'm closing this issue for now, if you need any more help let us know.
