### ISSUE TITLE
Browser back button event

### ISSUE THREAD

**Issue by pratiksha-94** [bitfoundation/bitplatform#6780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

How can I get browser back button pressed event in maui blazor app?

### .NET Version

8

**Comment by ysmoradi** [comment]
Have you tried overriding `OnBackButtonPressed` in `MainPage.xaml.cs`?
It's not directly related to bitplatform, but let me know about the results anyway.

**Comment by pratiksha-94** [comment]
No, not getting any event in backbuttonpressed but may be its related to any javascript evnt emitted by browser. Any help in this regard appreciated.

**Comment by pratiksha-94** [comment]
Thank You...
