### ISSUE TITLE
Unable to cast object of type 'Bit.Butil.ButilCookie' to type 'System.IConvertible'.

### ISSUE THREAD

**Issue by mstfch2020** [bitfoundation/bitplatform#6789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hey ,hope you are doing well
i got exception for this code below 

```csharp
public async Task SaveUserRole(UserType userType)
{
    var tokenMaxAge = await cookie.Get("token_max_age");

    if (tokenMaxAge is null) return;
            
    await cookie.Set(new()
    {
        Name = "user_role",
        Value = userType.ToString(),
        MaxAge = Convert.ToInt32(tokenMaxAge),
        SameSite = SameSite.Strict,
        Secure = BuildConfiguration.IsRelease()
    });
}
```

```
Exception Message==>Unable to cast object of type 'Bit.Butil.ButilCookie' to type 'System.IConvertible'.


Execption StackTrace==>   at System.Convert.ToInt32(Object value) in /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs:line 984
   at Fusion.Client.Core.Services.AuthenticationManager.<SaveUserRole>d__20.MoveNext() in D:\newSource\yasanNew\portal\src\Client\Fusion.Client.Core\Services\AuthenticationManager.cs:line 190
   at Fusion.Client.Core.Components.Pages.Identity.RoleSelection.<OnInitAsync>d__20.MoveNext() in D:\newSource\yasanNew\portal\src\Client\Fusion.Client.Core\Components\Pages\Identity\RoleSelection.razor.cs:line 44
   at Fusion.Client.Core.Components.AppComponentBase.<OnInitializedAsync>d__18.MoveNext() in D:\newSource\yasanNew\portal\src\Client\Fusion.Client.Core\Components\AppComponentBase.cs:line 44
```

**Comment by ysmoradi** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by ysmoradi** [comment]
It seems `Cookie.Get("key")` returns `ButilCookie` instead of `string`
Does it make any sense? @msynk

**Comment by msynk** [comment]
@ysmoradi
yes, why not?

**Comment by ysmoradi** [comment]
> @ysmoradi yes, why not? it's not GetValue, so it should return the Cookie object instead of its value. but what does it have to do with the issue?

It seems to be misleading; shall we add `GetValue` method too?

**Comment by msynk** [comment]
> > @ysmoradi yes, why not? it's not GetValue, so it should return the Cookie object instead of its value. but what does it have to do with the issue?
> 
> It seems to be misleading; shall we add `GetValue` method too?

no

**Comment by msynk** [comment]
@mstfch2020 it seems the problem is coming from this line:

`MaxAge = Convert.ToInt32(tokenMaxAge)`

the return value of the `Get` method is an instance of the `ButilCookie` class and this class cannot be converted to an int.
