### ISSUE TITLE
Changing `BitNav` arrow button position

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitplatform#6794]
I need to show arrows on the right side of the nav items.
![image](https://github.com/bitfoundation/bitplatform/assets/23101977/961a74d8-26ed-4484-99e6-0edbdd4e589b)

**Comment by msynk** [comment]
@msangtarash Thanks for contacting us.

you can simply achieve this by assigning a style like this to the `ItemContainer` property of the `Classes` or `Styles` parameter of the BitNav:

`flex-flow: row-reverse;`

**Comment by msangtarash** [comment]
> @msangtarash Thanks for contacting us.
> 
> you can achieve this by assigning a style like `flex-flow: row-reverse;` to the `ItemContainer` property of the `Classes` or `Styles` parameter of the BitNav.
> 
> plz let us know if this solution resolves your problem.

I already did that, but I couldn't find any way to handle padding on the left side of items as I have some items that don't have child Items.

**Comment by msynk** [comment]
@msangtarash It seems there isn't a straight forward solution for this requirements, so I'm going to add a new feature for this.
