### ISSUE TITLE
Issue with `BitDropdown` in `Combo` and `Multi Select` modes on mobiles

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#6855]
I've encountered an issue with the `BitDropdown` component when both `combo` mode and `multi-select` mode are active. 

Upon selecting an item, the callout closes immediately. This behavior prevents the selection of multiple items, as the callout should ideally remain open to allow for additional selections.

This issue hinders the functionality of the multi-select mode.

**Comment by msynk** [comment]
not relevant anymore!
