### ISSUE TITLE
Cannot build project after Visual Studio update

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#6861]
I cannot build my own and `bit platform` projects after updating Visual Studio!
It says `Cannot find module`!

![image](https://github.com/bitfoundation/bitplatform/assets/42671084/ad3047c3-b325-4195-98fd-22c9aa96c367)

**Comment by ysmoradi** [comment]
Could you please try running `Clean.bat` or `Clean.sh` based on your development OS?

**Comment by mhrastegari** [comment]
Thanks @ysmoradi `Clean.bat` worked on my Windows machine very well!
I no longer see errors ✌🏻
