### ISSUE TITLE
`BitDatePicker` culture is not correct on Android

### ISSUE THREAD

**Issue by mhrastegari** [bitfoundation/bitplatform#6927]
The year should be Shamsi but instead shows Gregorian!

![image](https://github.com/bitfoundation/bitplatform/assets/42671084/15cfc750-0c54-4e60-a438-7c83e75a8592)

**Comment by STRstark** [comment]
Not only the year is not correctly been changed into jalali c

**Comment by STRstark** [comment]
Not only the year is not correctly been changed into jalali culture , but also the date thats been picked by the components is not the one that the compunents puts into its place holder.

**Comment by ysmoradi** [comment]
![image](https://github.com/bitfoundation/bitplatform/assets/5352980/697544d0-eb24-46f6-85c3-bccf60f4d7bf)
There's not much we can do at this stage, I'd expect 1402, but I received 2024!
