### ISSUE TITLE
Add extension methods "HasValue" and "HasNoValue" in `Bit.BlazorUI.Demo.Client.Core`

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#7009]
I am trying to use the Bit.BlazorUI library in the demo project, but I cannot access the extension methods "HasValue" and "HasNoValue" that are defined in the library. These methods are marked as internal, so they are not visible to the demo project.

**Comment by msynk** [comment]
not valid!
