### ISSUE TITLE
How to run Blazor Maui - Hybrid app model

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#7127]
According to the documentation [Here](https://bitplatform.dev/templates/app-models) to run **Blazor Maui - Hybrid** Here is how we should config startup projects :

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/8c03d9bb-9f4c-405f-abe8-2dbeb49173d9)
But there is not **Server-Swagger** showing for me : 

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/980a9681-3cf7-4a19-bba8-b656b8edb215)

This is how I created my project
`dotnet new bit-bp --name ArshidFoodReservation --database other --sample Admin`
Where am I wrong ?
I should mention that **Blazor Server mode** works fine but neither **WebAssembly** nor **Maui** works

**Comment by ysmoradi** [comment]
Thanks for detailed issue
Have you tried our videos? I've demonstrated everything visually
https://www.youtube.com/@bitplatform/playlists

**Comment by zandiarash** [comment]
> Thanks for detailed issue Have you tried our videos? I've demonstrated everything visually https://www.youtube.com/@bitplatform/playlists

I watched until 5 episode but I do not have "server-swagger" like demo
![image](https://github.com/bitfoundation/bitplatform/assets/10775073/68ad753c-a572-4aec-b3f0-9fe3ff6ebf5f)

**Comment by ysmoradi** [comment]
That's fine, it's a little change. You can use `ArshidFoodReservation.Server` for the same purpose and open `/swagger` url manually if you want.

**Comment by zandiarash** [comment]
Thank you, I wish if Bitplatform documentation become updated soon.
