### ISSUE TITLE
Toggle Menue will not show up and doesn't works

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#7153]
In the both **Todo** and **Admin** sample **Toggle Menue** will not show up.

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/40f6c455-a48c-42c3-8463-762218956038)

After changing CSSit is showing but does not works
![image](https://github.com/bitfoundation/bitplatform/assets/10775073/5da29e1b-48b5-45bc-ba30-253d3bfbf930)

**Comment by msynk** [comment]
@zandiarash Thanks for contacting us.
I don't understand the issue. I've tested the menu on small screens and it works fine in Todo and AdminPanel.
Could you please provide more information about the problem?

**Comment by msynk** [comment]
I don't understand the issue. I've tested the menu on small screens and it works fine in Todo and AdminPanel.
Could you please provide more information about the problem?

**Comment by zandiarash** [comment]
I'm so sorry I thought for large windows it should appear and behaves like [CoreUI](https://coreui.io/)
I've miss understood, by the way is there any plan to make menue more attractive?

![image](https://github.com/bitfoundation/bitplatform/assets/10775073/79c623ec-8c55-470b-b7cf-a5dd936b45c7)
![image](https://github.com/bitfoundation/bitplatform/assets/10775073/89c9c6da-98df-4d08-8c7f-e019b89035c7)

**Comment by msynk** [comment]
Thanks for the clarification.
We plan to update the UI/UX of our project templates soon. so stay tuned.
