### ISSUE TITLE
CI/CD Action Error

### ISSUE THREAD

**Issue by amirzaeii** [bitfoundation/bitplatform#7373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi guys,
When I want use Github actions for ci/cd i got a error that i attched 
I install all workloads and prerequesties 
anybody knows why?
![Screenshot 2024-04-13 143109](https://github.com/bitfoundation/bitplatform/assets/16682716/01a6e631-1d7c-4e58-be02-21edaf2decbf)

### .NET Version

8.0.203

**Comment by amirzaeii** [comment]
my os is wnidows 11 pro edition with visual studio 17.9.0

**Comment by msynk** [comment]
@amirzaeii Thanks for contacting us.
to build the Web project you first need to install the `wasm-tools` workload of the .NET SDK.
you can check our own CI pipeline in this file: 
https://github.com/bitfoundation/bitplatform/blob/develop/.github/workflows/bit.ci.yml

this specific step:
![image](https://github.com/bitfoundation/bitplatform/assets/6169846/329a1daa-c17e-4412-b402-cc8a71bd6ee3)

**Note**: if you don't need to build the MAUI project you can omit the `maui-android` workload. also, the `wasm-experimental` workload is optional.

**Comment by amirzaeii** [comment]
Thank you @msynk 
But I install all workloads like this page 
https://bitplatform.dev/templates/development-prerequisites

**Comment by msynk** [comment]
@amirzaeii 
did you add that specific step to your github action?

btw, remember to run the command inside the src folder.

**Comment by amirzaeii** [comment]
Nah I didn't add any other step...

**Comment by msynk** [comment]
you need to add it. since each run of the pipeline runs on a random VM instance so to make sure everything is available there, you need to have all the required steps in the github action yml file.
lemme know plz if your problem is solved.
