### ISSUE TITLE
Add `Debounce` and `Throttle` features to the input components

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#7556]
I would like to propose the addition of `Debounce` and `Throttle` features to the input components (TextField, NumberField, SearchBox, ...). These features can help optimize the performance of our application by limiting the rate at which a function can fire.

- **Debounce** calls a function when a user hasn’t carried out an event in a specific amount of time.
- **Throttle** calls a function at intervals of a specified amount of time while the user is carrying out an event.

**Comment by keenan-chiasson** [comment]
+1 I second this
