### ISSUE TITLE
Not loading icons in old browsers

### ISSUE THREAD

**Issue by mostafa1374** [bitfoundation/bitplatform#7595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use the rating, but I noticed that the star icons are not loaded in mobile mode in some browsers (for example: chrome 109).
![image](https://github.com/bitfoundation/bitplatform/assets/25504875/a5f28496-3e0f-4bb1-90f7-2b580576c8b9)

**Comment by msynk** [comment]
@mostafa1374 Thanks for contacting us.
I've tested it in some old browsers on https://browserstack.com but found no issue.
could you plz provide your code too?
btw, did you configure the components correctly? (see https://blazorui.bitplatform.dev/getting-started)

**Comment by mostafa1374** [comment]
Thank you for your review.
After my investigations, I realized the problem from my side.
Thanks again for the review
