### ISSUE TITLE
Swagger LogIn fails: swagger-utils.js - await originalAuthorize(args) is "undefined"

### ISSUE THREAD

**Issue by Lockheed0815** [bitfoundation/bitplatform#7693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Swagger UI LogIn fails: in file swagger-utils.js - await originalAuthorize(args) is "undefined"

### Expected Behavior

successful access out of swagger API in order to set cookie 

### Steps To Reproduce

Fresh setup:
- Install Bit.Boilerplate 8.9.0-pre-02
- Create Admin Template
- Create new and empty database
- DB Migration as described
- Attempt login Swagger UI with unmodified test user: "test", Password: "123456"
- Error thrown in swagger-utils.js: await originalAuthorize(args) is "undefined"

### Exceptions (if any)

Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'payload')
    at swagger.authActions.authorize (C:\Users\Martin\source\repos\BitTest1\BitTest1\src\BitTest1.Server\wwwroot\swagger\swagger-utils.js:42:56)
    --- await ---
    at signIn (C:\Users\Martin\source\repos\BitTest1\BitTest1\src\BitTest1.Server\wwwroot\swagger\swagger-utils.js:161:29)
    --- await ---
    at signInButton.onclick (C:\Users\Martin\source\repos\BitTest1\BitTest1\src\BitTest1.Server\wwwroot\swagger\swagger-utils.js:143:9)

### .NET Version

8.0.301

### Anything else?

- Visual Studio 2022 17.10.1
- SQLEXPRESS
- NuGet Package 8.9.0-pre-02 
- 
![Screenshot 2024-06-04 150646](https://github.com/bitfoundation/bitplatform/assets/126007054/9c5b8d4c-2d68-4e50-91e2-496ae84e90a6)

**Comment by ysmoradi** [comment]
We've refactored the way users can sign in to the app.
Users are able to sign in with either username, email or phone number alongside with either password or otp.
We've also added social sign in and 2fa support.
Unfortunately, the swagger sign in is not updated based on latest changes, so I'm submitting a PR for it.

**Comment by ysmoradi** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
