### ISSUE TITLE
Admin Template - Typo in TokenOptions: DefaultPhoneProvider used instead DefaultEmailProvider

### ISSUE THREAD

**Issue by techscx** [bitfoundation/bitplatform#7792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During user Registration using an Email & Password, the ConfirmEmailToken is generated:

IdentityController.cs,
Line 521:
 var token = await userManager.GenerateUserTokenAsync(user, TokenOptions.DefaultPhoneProvider, FormattableString.Invariant($"VerifyEmail:{email},{user.EmailTokenRequestedOn}"));

Line 103:
      var tokenIsValid = await userManager.VerifyUserTokenAsync(user, TokenOptions.DefaultPhoneProvider, FormattableString.Invariant($"VerifyEmail:{request.Email},{user.EmailTokenRequestedOn}"), request.Token!);

### Expected Behavior

It should read TokenOptions.DefaultEmailProvider.

### Steps To Reproduce

- Setup latest dotnet Bit.Boilerplate::8.9.0
- register new user by Email & Password
- Try to use the token to enable the account

### Exceptions (if any)

The token returns to be invalid.

### .NET Version

8.0.301

**Comment by ysmoradi** [comment]
Thanks for submitting issue.
Note that we're using `TokenOptions.DefaultPhoneProvider` by design in order to generate 6 digits codes, so the user will be able to either:
1- Open the link to confirm email account
2- Copy/paste 6-digit codes
3- Remember/type 6-digit codes
in order to confirm its email address.

**Comment by techscx** [comment]
> Thanks for submitting issue. Note that we're using `TokenOptions.DefaultPhoneProvider` by design in order to generate 6 digits codes, so the user will be able to either: 1- Open the link to confirm email account 2- Copy/paste 6-digit codes 3- Remember/type 6-digit codes in order to confirm its email address.

Thank you.
My procedure:
If I register with Email & Password without providing a Phone Number, the token verification fails.
Once, I have changed to the DefaultEmailProvide, the token verification succeeds.

**Comment by ysmoradi** [comment]
Just signed in with `ysmoradi+122445@gmail.com` and `123456` and without any phone number to https://adminpanel.bitplatform.dev without any issue.
You can also sign-in with the credentials I provided to check if you see any problem or not.
Let me know about the results and also provide me details about your Boilerplate version.

**Comment by techscx** [comment]
> Just signed in with `ysmoradi+122445@gmail.com` and `123456` and without any phone number to https://adminpanel.bitplatform.dev without any issue. You can also sign-in with the credentials I provided to check if you see any problem or not. Let me know about the results and also provide me details about your Boilerplate version.

That is interesting. So there must be an issue in my copy of the Template. 
Thank you!

**Comment by ysmoradi** [comment]
We're happy to help at any time, let me know if you found any more details
