### ISSUE TITLE
Input characters are deleted during entry - Render Mode Server only

### ISSUE THREAD

**Issue by techscx** [bitfoundation/bitplatform#7805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During text input, e.g. logging in, characters are deleted while validation is done.

### Expected Behavior

Input should not be influenced.

### Steps To Reproduce

- Setup new Bit.Boilerplate::8.9.0
- Host in Server Rendered Mode only (debug or forced server rendered in release)
- Publish the host to IIS or make it available via tunnel (e.g. https devtunnel from Visual Studio)
- Access host from windows-chrome
- Open login page and start entering an Email-address
- Characters are deleted
Note:
The behaviour is not visible by just debugging in devmode locally. It must be exposed as published on a real host or at least via a tunnel e.g. devtunnel while debugging in Visual Studio.

https://github.com/bitfoundation/bitplatform/assets/71921910/7e34a458-6c79-4c95-b180-467238693200

### Exceptions (if any)

None.

### .NET Version

8.0.301

**Comment by msynk** [comment]
@techscx Thanks for contacting us.
We know about this issue. This problem is related to how BlazorServer works, and an issue already exists for it (https://github.com/bitfoundation/bitplatform/issues/7660).
We are already working on a PR (https://github.com/bitfoundation/bitplatform/pull/7804) to remedy this issue by providing a new feature for disabling Immediate feedback of the inputs to lessen the problem you've shown in this issue.

**Comment by techscx** [comment]
> @techscx Thanks for contacting us. We know about this issue. This problem is related to how BlazorServer works, and an issue already exists for it (#7660). We are already working on a PR (#7804) to remedy this issue by providing a new feature for disabling Immediate feedback of the inputs to lessen the problem you've shown in this issue.

Oh, thank you for clarification.

**Comment by msynk** [comment]
@techscx 
the new prerelease that resolves this issue is now available. you can now use the inputs without Immediate binding while typing so this problem should not be happening anymore.

**Comment by techscx** [comment]
Thank you!

> @techscx the new prerelease that resolves this issue is now available. you can now use the inputs without Immediate binding while typing so this problem should not be happening anymore.
