### ISSUE TITLE
Reset `StyleBuilder` in `BitSticky` component after changing `Top`, `Bottom`, `Left`, and `Right` parameters

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#8005]
In the BitSticky component, after changing the Top, Bottom, Left, and Right parameters in the StyleBuilder class, it appears that the class is not being reset properly. This can lead to unexpected behavior and potential issues in the layout of the elements.

**Comment by msynk** [comment]
I'm closing this issue, since it is being taken care of in #8012
