### ISSUE TITLE
Pull-down refresh and swipe left/right navigation

### ISSUE THREAD

**Issue by techscx** [bitfoundation/bitplatform#8104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to implement these swipe navigation features
- pull-down refresh on page level
- swipe left=navigate back
- swipe right=navigate forwared 

### Describe the solution you'd like

The most preferred solution would be to have components providing swipe interaction along with refresh and navigation options.

**Comment by msynk** [comment]
@techscx Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
The issue is accepted and planned. Resolving it will start ASAP.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.
