### ISSUE TITLE
MS Entra Auth

### ISSUE THREAD

**Issue by bakes82** [bitfoundation/bitplatform#8326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Ability to use MS Entra Auth as a social login and ability to disable/not show others,

### Describe the solution you'd like

When logging/creating accounts ability to use MS Entra/Windows auth.

**Comment by ysmoradi** [comment]
We followed these [google ](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins)and [twitter ](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins)docs to implement that in Boilerplate, you can follow [this one](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins)
Don't forget to submit PR after you finished your testing (":
