### ISSUE TITLE
Feedback/Questions

### ISSUE THREAD

**Issue by bakes82** [bitfoundation/bitplatform#8327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

After doing a quick test here is some generalized feedback.

Theme: This seems to be configured via CSS, why not use the theme manager, it would also be great if the UI Docs page could generate some basic styles by just setting the primary/secondary etc colors and it just does a 5-10% darken/lighten.

I didnt see anywhere to "easily" disable the authentication options or where to set the clientIds/settings etc.

Ability to not generate "clients", it would be nice to only just generate a web project, and maybe pass in ServerRender Only, Auto.

When I try to filter on the "Products" page its posting back after every letter press, it doesnt seem to happen on the UI DataGrid demo pages though.

Is the default username/password set someplace, I created a new users and just manually approved in the SQL, but I then saw the email messages after the fact but they were encoded.

I enabled AzureBlobStorage = true, where is that configured?

**Comment by ysmoradi** [comment]
I don't know what you mean by ThemeManager, maybe @msynk  can help, but about configuring clients, our identity implementation is not something OAuth based, so it has nothing to do with clients configuration. But about the identity parameter in dotnet new command, I consider your request.
Yes, we're adding Debounce & Throttle features to our search box, but in a meantime, you can handle it in your own code easily. @msynk might be able to provide you such a code snippet.
The default user/pass are located in Server.Api/Data/Configurations/Identity/UserConfiguration.
What do you mean they were encoded? Could you please send me screenshot?
About azure blob storage, what kind of configuration do you need? you can configure it's connection string in Serer.Api's appsettings' ConnectionStrings section (It connects to azure blob storage emulator by default)

**Comment by bakes82** [comment]
The .eml files saved in app_data are base64 encoded, just a minor annoyance if you dont know what the default user/password is and create a new one.

Ahh server.api files :) It was late when I was reviewing, but found the appsettings now, but I would tie the socials to check if there is no clientid in them to not display/add a enable flag.

Are you saying the expected behavior when you download the project is when you use the "search" on the products grid you Type in 1 letter the box closes, this isnt what I would expect, I would expect some kind of like delay so you could type in something then maybe 1-2 seconds after it auto searches, right not its basically unusable since you type in one letter, it closes and then you have to reopen it type a 2nd letter it closes.

If you want to use the BitThemeProvider, the mainlayout doesnt have it included.  So I just for testing threw one on it and added, it seems like you guys have a scss file with the "base" colors instead of just a default collection of BitThemes.  

[CascadingParameter] public BitTheme?                 Theme                   { get; set; } = new()
        {
            Color = { Primary = { Main = "Green" }, Error = { Main = "DarkRed", DarkHover = "Yellow", MainHover = "Purple"}}
        };

**Comment by msynk** [comment]
@bakes82 Thanks for contacting us.
You can easily open the `.eml` files using an email client like Outlook on Windows.

The feature to apply a delay for binding values is already available in our text inputs, the only component missing this feature is the BitSearchBox which will be completed in the next prerelease. if you want you can replace the BitSearchBox with a BitTextField and use its Immediate parameter together with the DebounceTime to achieve this behavior for now. but the weird behavior of rendering the DataGrid after each search needs a bit more investigation from our side.

I don't quite understand what you need from the theme. you want to override the default values or customize it for a specific section of a page?

**Comment by bakes82** [comment]
Yes I could install an email client, but not all organizations allow those to be on developer machines, I guess I was expecting a bit more documentation on where to find/set default values.

The grid isnt rerendering its just filtering heres whats happening:
![issue](https://github.com/user-attachments/assets/fb868bde-d52d-42ec-b7f8-bf08b2f324ee)

Im assuming this "solution" is a show case of your features of BlazorUi also, I was just expecting the theme manager to be on the layout and you guys were actually using it to set your theme.  Yes I was looking to change the colors and like in other tools like syncfusion/devexpress etc their temples already have these in the layout and you can create a new class like I did above, again its just me trying to figure out how to use the template and whats implemented or what needs to be implemented to make changes.  Clearly I could go change the scss file, but wouldn't the preferred approach be to use the theme manager, so I then question why the solution isn't itself using the theme manager to set the theme colors.

**Comment by ysmoradi** [comment]
We're building [docs](https://bitplatform.dev/templates/overview) for the Boilerplate project template. we're going to provide what are default credentials.
In the email, we're sending link and code to confirm the account, and those values are written to the backends' console and Visual Studio debug output pane as well (In dev environment)
Note that you can connect to [ethereal](https://ethereal.email/) by the following settings in your Server.Api's appsettings.json, that shows your email on the web for testing purposes

```json
"Host": "smtp.ethereal.email",
"Port": "587",
"DefaultFromEmail": "alva.schiller52@ethereal.email",
"DefaultFromName": "Alva Schiller",
"UserName": "alva.schiller52@ethereal.email",
"Password": "4PyGY8cDQ8mvu6h7qB"
```
You can also use web based eml viewers such as https://www.encryptomatic.com/viewer/

**Comment by msynk** [comment]
about the DataGrid, you can see that it is getting re-rendered on each search. it is obvious in your short video of its behavior too. just check out how the search popup is getting closed after each search. it is clear on a published website (like https://adminpanel.bitplatform.dev) when the connection is slower compared to a local run.

about the ThemeManager, we are using it in our template to toggle between the dark and light themes. the thing is we don't need it to override anything in our template yet but we may add such a sample in the future.

**Comment by bakes82** [comment]
@msynk I was testing here: https://blazorui.bitplatform.dev/components/datagrid, this page has it working correctly, because the demo site doesnt tell you the creds to login and I wasnt going to signup for it, but it looks like the same issue is on the demo site also.

**Comment by msynk** [comment]
we don't have that issue on the BitDataGrid demo page.

**Comment by msynk** [comment]
The DataGrid search issues on the Products and Categories pages of the Boilerplate project template are resolved now. you can check them out in the new UI design by downloading the latest prerelease of its nuget package.

**Comment by msynk** [comment]
I'm closing this issue since there has not been any activity here for a long time.
