### ISSUE TITLE
Missing "image" in the "devcontainer.json" file

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#8367]
After I select **"Reopen in container"** the **VScode** show an error
![22](https://github.com/user-attachments/assets/b9def849-3958-4c40-9cf9-10c3825cb067)
But when I add this line 
`"image": "mcr.microsoft.com/vscode/devcontainers/base:ubuntu",`
To my devcontainer.json file it works well.
Can I make a pull request and add this line to the projects ?

**Comment by ysmoradi** [comment]
But it's working anyway, right?

**Comment by ysmoradi** [comment]
But it's working anyway, right?

**Comment by zandiarash** [comment]
> But it's working anyway, right?

Actually for me does not works,
Even I updated my VsCode and it's extension and dotnet.

**Comment by zandiarash** [comment]
> Actually for me does not works,
> Even I updated my VsCode and it's extensions, dotnet and also fetched the latest source codes.
> Maybe I did something wrong.

Actually for me does not works,
Even I updated my VsCode and it's extensions, dotnet and also fetched the latest source codes.
Maybe I did something wrong.

**Comment by zandiarash** [comment]
> But it's working anyway, right?

Actually for me does not works,
Even I updated my VsCode and it's extensions, dotnet and also fetched the latest source codes.
Maybe I did something wrong.

**Comment by ysmoradi** [comment]
Could you please open this repo in github codespace?
https://github.com/bitfoundation/bit-templates-playground

**Comment by zandiarash** [comment]
> Could you please open this repo in github codespace? https://github.com/bitfoundation/bit-templates-playground

That works well.

**Comment by ysmoradi** [comment]
So, there's something wrong on your side, could you please compare yours with this project?

**Comment by ysmoradi** [comment]
Now I see the issue you're talking about (":

**Comment by zandiarash** [comment]
> Now I see the issue you're talking about (":

May you check the pull request [#8476](https://github.com/bitfoundation/bitplatform/pull/8476) ?
