### ISSUE TITLE
Maximizable Button for dialog component

### ISSUE THREAD

**Issue by Hamid-kadkhoda** [bitfoundation/bitplatform#8675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Maximize and Minimize conditional Button for dialog component beside of close button like in primeng dialog component
write it optional as Maximizable . it's very usefull

[Parameter] public bool Maximizable { get; set; } = false;

**Comment by Hamid-kadkhoda** [comment]
![image](https://github.com/user-attachments/assets/b697d5ee-a011-41ac-9300-9b097af45926)

**Comment by msynk** [comment]
@Hamid-kadkhoda Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
after some investigations we've decided that adding this feature to the BitDialog component is not aligned with our conventions and design approach.
So unfortunately I have to close this issue.

**Comment by msynk** [comment]
btw, we've implemented a similar feature in the `BitModal` component named `FullSize` which you can check it out in action here:

https://blazorui.bitplatform.dev/components/modal#example6
