### ISSUE TITLE
DataGrid Component in BitPlatform BlazorUi

### ISSUE THREAD

**Issue by STRstark** [bitfoundation/bitplatform#8682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Hi, Hope guys are Perfect :)

i am trying to create a **`DataGrid`** for a invoice handling project,

but i want the data inside the Grid to be able to change at its place 

> for Example the excel files we can change a value of a certain column at it place , we click on it and it becomes like a `<Input/>` tag :)

i prefer **NOT** to use complicated **`JavaScript`** code to change the tag to make it an input ... and all of those fancy complicated codes :)

can you help me achieve what i am trying to create ?

**Comment by msynk** [comment]
@STRstark Thanks for contacting us.

I'm sorry to tell you that the requested feature is beyond our planned support for the BitDataGrid and it's improbable that we add such a big feature to this component.

We will update you on the status of this issue if we decide to take any action on it in the future.

**Comment by msynk** [comment]
I'm closing this issue since we don't have any plan to support such a feature.
