### ISSUE TITLE
TODO online demo dont work UnknownException

### ISSUE THREAD

**Issue by jorge-teixeira** [bitfoundation/bitplatform#8971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the https://[todo.bitplatform.dev](https://todo.bitplatform.dev/)/  dont work

'{
    "exceptionType": "TodoSample.Shared.Exceptions.UnknownException",
    "key": "UnknownException",
    "message": "Unknown error has occurred",
    "payload": null
}'

### Steps To Reproduce

access to: https://todo.bitplatform.dev/

**Comment by ysmoradi** [comment]
Could you please try again?

**Comment by jorge-teixeira** [comment]
All ok now
Please close usue

A segunda, 21/10/2024, 13:09, Yaser Moradi ***@***.***>
escreveu:
