### ISSUE TITLE
PDFViewer Control based on PDFjs

### ISSUE THREAD

**Issue by samdubey** [bitfoundation/bitplatform#8991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to know if we could have PDFJs based PDFViewer Control for BitPlatform

Reference:
https://mozilla.github.io/pdf.js/

### Describe the solution you'd like

BitPdfViewer Control

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
