### ISSUE TITLE
Adding and use another component beside BlazorUI

### ISSUE THREAD

**Issue by zandiarash** [bitfoundation/bitplatform#9122]
Hello Dear support team
Is there a way to add and use another component library beside BlazorUI in the  cross platform solution?
For example Antblazor or Radzen.

Where should I add Services
`builder.Services.AddRadzenComponents()`;

Where to add what should be added to **App.razor** within the < head > element for example this line 
`<RadzenTheme Theme="material" @rendermode="InteractiveAuto" />`

Where to add what should be added to **MainLayout.razor** for example this line 
`<RadzenComponents @rendermode="InteractiveAuto" />`

Where should I add **scripts**

Should I add them to the core project ?

**Comment by msynk** [comment]
@zandiarash thanks for contacting us.
Achieving what you expressed is straightforward and can be done in normal ways available in Blazor projects.
But you can search for the Bit.BlazorUI in the source code and find the places we used references to this library.

for example, you can add `builder.Services.AddRadzenComponents()` to the `IClientCoreServiceCollectionExtensions.cs` file in the client core project as we did for `services.AddBitBlazorUIServices()`.

for the other components, I'm not familiar with that specific component and you should follow their own documents.

**Comment by zandiarash** [comment]
> @zandiarash thanks for contacting us. Achieving what you requested seems straightforward and can be done in normal ways, which are available in Blazor projects. But you can search for the Bit.BlazorUI in the source code and find the places we used references to this library.
> 
> for example, you can add `builder.Services.AddRadzenComponents()` to the `IClientCoreServiceCollectionExtensions.cs` file in the client core project as we did for `services.AddBitBlazorUIServices()`.
> 
> for the other components, I'm not familiar with that specific library and you should follow their own documents.

Thank you @msynk the key was the `IClientCoreServiceCollectionExtensions` file and since I've added **styles** and **scripts** in **Index.html** files that works well.
Actually Bit.BlazorUI is kind of a mature library but **DataGrid** has not some features for example does not supports [dynamic data support](https://blazor.radzen.com/datagrid-dynamic) that was the reason I've added Radzen.
By the way thanks for the fast and usable response.

**Comment by zandiarash** [comment]
> @zandiarash thanks for contacting us. Achieving what you requested seems straightforward and can be done in normal ways, which are available in Blazor projects. But you can search for the Bit.BlazorUI in the source code and find the places we used references to this library.
> 
> for example, you can add `builder.Services.AddRadzenComponents()` to the `IClientCoreServiceCollectionExtensions.cs` file in the client core project as we did for `services.AddBitBlazorUIServices()`.
> 
> for the other components, I'm not familiar with that specific library and you should follow their own documents.

Thank you @msynk the key was the `IClientCoreServiceCollectionExtensions` file and since I've added **styles** and **scripts** in **Index.html** files that works well.
Actually Bit.BlazorUI is kind of a mature library but **DataGrid** has not some features for example does not supports [dynamic data support](https://blazor.radzen.com/datagrid-dynamic) that was the reason I've added Radzen.
By the way thanks for the fast and usable response.
