### ISSUE TITLE
Parameters in `BitDateRangePicker` component are not sorted alphabetically

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitplatform#9293]
I've noticed that the parameters in the `BitDateRangePicker` component are not sorted alphabetically in the code-behind file. This can make the code harder to read and maintain.

For better readability and maintainability, it would be beneficial to sort these parameters alphabetically. This would also ensure consistency across the codebase if this is a standard practice.

**Comment by msynk** [comment]
not relevant
