### ISSUE TITLE
SignalR not working in azure

### ISSUE THREAD

**Issue by Kyemate** [bitfoundation/bitplatform#9353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not able to get SignalR working in azure with Azure SignalR Service.

So far I tried turning on azure signalR with builder.Services.AddSignalR().AddAzureSignalR();

Turning on web socket on the Azure AppService.

With this solution I get a 101 handsake on the websocket but no messages comes through.

Removing this code from the client.
options.SkipNegotiation = true;
options.Transports = HttpTransportType.WebSockets;

After doing that I get spammed with these messages while logged out. And while logged in I still don't receive any messages. 
![image](https://github.com/user-attachments/assets/9fadbd1b-c9a0-4d1c-ab1a-a24d433f36bb)

### Steps To Reproduce

Create an azure webapp and an azure signalR service.
Add builder.Services.AddSignalR().AddAzureSignalR(); 

### .NET Version

.net 9

**Comment by ysmoradi** [comment]
Could you please clarify intentions behind removing these lines?
```cs
options.SkipNegotiation = true;
options.Transports = HttpTransportType.WebSockets;
```

**Comment by Kyemate** [comment]
> Could you please clarify intentions behind removing these lines?
> 
> ```cs
> options.SkipNegotiation = true;
> options.Transports = HttpTransportType.WebSockets;
> ```

From what I've read the negotiation is needed for azure signalR to work
![image](https://github.com/user-attachments/assets/387abed0-14af-4f74-b33c-b00de54fa106)

**Comment by Kyemate** [comment]
I've tried with only web-sockets and with that solution I still don't get any messages out and while signed out I get spammed with about 10 unauthorized exceptions every second

**Comment by Kyemate** [comment]
With only Websockets and SkipNegotiation disabled I also get this error
![image](https://github.com/user-attachments/assets/0f7eda8d-7953-49ef-96f1-821d1aab0468)

**Comment by Kyemate** [comment]
This is another warning I get when I have removed both websockets and SkipNegotiation 
![image](https://github.com/user-attachments/assets/72117439-f624-4b2e-9e14-d8b73338556f)

**Comment by ysmoradi** [comment]
It seems that Azure SignalR is trying to scale out Blazor Server's SignalR as well which is worthless and will cost you a lot and will slow down your apps as well
First, we need to find a way to limit Azure SignalR to the `AppHub` only, without such a thing, let's consider Boilerplate's SignalR support useful for Standalone Api mode only.

**Comment by Kyemate** [comment]
> I just tested Azure SignalR and this is our conclusion: 1- We're not going to support any other provider except web sockets for SignalR, that's by design and reduce lots of complexities in Boilerplate and in almost all scenarios, web socket support is enough.
> 
> 2- Azure SignalR is not working at all in our integrated api mode (**It works on Standalone api mode though**), and **it's not** because of web sockets (the root cause needs more investigation).
> 
> For now, you can test our SignalR without Azure scaling to see if its web socket only mode works for you or not (it supposed to work, just like published demo apps we've, adminpanel demos that contain SignalR)
> 
> You could also deploy using standalone api mode which works perfectly fine with Azure SignalR (I'm about to send a PR for it)

Alright, thank you for investigating it.

**Comment by ysmoradi** [comment]
I just sent a [PR ](https://github.com/bitfoundation/bitplatform/pull/9366/files)for it

[These notes](https://github.com/ysmoradi/bitplatform/blob/9365-boilerplate-project-templates-support-for-scale-out-is-missing/src/Templates/Boilerplate/Bit.Boilerplate/src/Server/Boilerplate.Server.Web/Program.Middlewares.cs#L131-L139) are important part of the PR

```cs
// Azure SignalR is going to send blazor server / auto messages to the Azure Cloud which is useless in this case,
// because scale out lots of messages that are related to the current opened tab of browser only is not necessary and will cost you lots of money.
// https://github.com/Azure/azure-signalr/issues/1738
// Solutions:
// - Switch to Blazor WebAssembly in production. Hint: To leverage Blazor server's enhanced development experience in local dev environment, you can disable Azure SignalR by setting "Azure:SignalR:ConnectionString" to null in appsettings.json or appsettings.Development.json.
// OR
// - Use Standalone API mode:
//    Publish and run the Server.Api project independently to serve restful APIs and SignalR services like AppHub (Just like https://adminpanel-api.bitplatform.dev/swagger deployment)
//    and use the Server.Web project solely as a Blazor Server or pre-rendering service provider.
```

**Comment by ysmoradi** [comment]
The Azure SignalR is now working fine based on latest pre-release of Boilerplate
