### ISSUE TITLE
Unable to Install Bit Platform Setup Despite Multiple Attempts

### ISSUE THREAD

**Issue by rohanrathi99** [bitfoundation/bitplatform#9362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am facing an issue while setting up the Bit Platform on my system. I have attempted the installation process three times, including a complete reinstallation from scratch on the third attempt.

I followed all the steps provided in the official documentation on the website, but the issue persists. I am sharing some screenshots for reference to help diagnose the problem.

Could you please assist me in resolving this issue? Let me know if you need any additional details or logs from my end.

**Steps to Reproduce:**

Followed the installation steps as mentioned on the official website.
Attempted the setup process three times, with a complete reinstallation on the third attempt.

**Screenshots:**
![image](https://github.com/user-attachments/assets/2443a732-f470-4bb4-89ba-67cb805bbd00)
![while creating new project](https://github.com/user-attachments/assets/18718b56-d1ab-453d-a620-e37c615d0398)
![image](https://github.com/user-attachments/assets/1b81c4ae-a54a-4bc5-9ac4-b8cd203d3c58)

**System Details:**

Operating System: Windows 11 Pro
Node.js Version: v23.3.0
.Net: 
- 8.0.404 
- 9.0.100

Other relevant details: 
- Visual Studio: Community 2022 (v17.12.2)
- NPM: v10.9.1

### Expected Behavior

The Bit Platform setup should install successfully without errors.

### Steps To Reproduce

1. Followed the installation steps as mentioned on the official website.
2. Attempted the setup process three times, with a complete reinstallation on the third atte

### Exceptions (if any)

The Bit Platform setup should install successfully without errors and I can start my work.

### .NET Version

9.0.100

### Anything else?

![image](https://github.com/user-attachments/assets/325e0387-5f6a-4646-bc56-ebc28a957ba1)
![image](https://github.com/user-attachments/assets/408ee72b-36fc-4a31-bf8b-fbba3998931b)
![image](https://github.com/user-attachments/assets/98cc8f2f-f8cf-48f5-ba9d-f091d356bf36)

**Comment by ysmoradi** [comment]
It would be a good idea to try - - framework net9.0 while creating project
Let me know about the results

**Comment by msynk** [comment]
it seems the path in which the `dotnet workload restore` is running is not correct.

**Comment by rohanrathi99** [comment]
Thank you for the reply. 
I have checked the path in which the `dotnet workload restore` was running, corrected it, and now it has started working as expected. I appreciate your assistance!

**Comment by msynk** [comment]
I'm closing this issue for now. please feel free to re-open it if needed.
