### ISSUE TITLE
External login through new tab/popup

### ISSUE THREAD

**Issue by Kyemate** [bitfoundation/bitplatform#9399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently, external login redirects users away from the app, causing it to restart, which can be problematic for slow-loading WASM applications.

### Describe the solution you'd like

Have the option to open the login window in a new tab/popup

**Comment by ysmoradi** [comment]
This issue has been resolved and it will be available in the next pre-release version. It will be announced when the pre-release becomes ready.
