### ISSUE TITLE
Build failure on a new project built with boilerplate

### ISSUE THREAD

**Issue by mehrandvd** [bitfoundation/bitplatform#9429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've just created a new project following the instructions at: https://bitplatform.dev/templates/getting-started

I'm facing this error when building:
![image](https://github.com/user-attachments/assets/564fb31b-d3d1-4750-944a-eecbb4ed6dfb)

![image](https://github.com/user-attachments/assets/81e17c72-26cc-4ca6-9e78-36137c8d7925)

### Steps To Reproduce

The created project is here:
https://github.com/mehrandvd/check-bit

### .NET Version

9.0.101

**Comment by ysmoradi** [comment]
Please follow this while creating project

![17336659301151305125856719496308](https://github.com/user-attachments/assets/f5ca2b09-12f7-45a9-849d-d176251a48b9)

https://bitplatform.dev/templates/create-project

I'll take a look at this issue soon

**Comment by ysmoradi** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
It's because of the project's name, and I don't think we can do much about it.
You can see the same problem when creating a project named for example `Learn.Microsoft`.

**Comment by msynk** [comment]
I'm closing this issue for now, but please feel free to re-open it if needed.

**Comment by mehrandvd** [comment]
> I'm closing this issue for now, but please feel free to re-open it if needed.

Thank you, I've understood the issue and will implement alternative naming conventions.
